/** Guarded inspection for provider instruction files previously generated by ADE. */

import { lstatSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  AGENT_ROLE_END_MARKER,
  AGENT_ROLE_START_MARKER,
} from './agentInstructions';

export const LEGACY_CLAUDE_FILE = 'CLAUDE.md';
export const MEMORY_START_MARKER = '<!-- ADE:MEMORY:start -->';
export const MEMORY_END_MARKER = '<!-- ADE:MEMORY:end -->';

const MAX_INSTRUCTION_BYTES = 512 * 1024;
const MANAGED_BLOCKS = [
  [MEMORY_START_MARKER, MEMORY_END_MARKER],
  [AGENT_ROLE_START_MARKER, AGENT_ROLE_END_MARKER],
] as const;

export interface LegacyInstructionInspection {
  path: string;
  status: 'absent' | 'managed' | 'preserved';
}

/**
 * True only when the complete file consists of one or more well-formed ADE
 * memory/role blocks plus whitespace. Any user text, malformed marker, link,
 * or oversized file must be preserved by callers.
 */
export function isEntirelyAdeManagedInstruction(content: string): boolean {
  let remainder = content;
  let removedBlock = false;

  for (const [startMarker, endMarker] of MANAGED_BLOCKS) {
    while (true) {
      const start = remainder.indexOf(startMarker);
      const end = remainder.indexOf(endMarker);
      if (start === -1 && end === -1) break;
      if (start === -1 || end === -1 || end < start) return false;
      const nestedStart = remainder.indexOf(startMarker, start + startMarker.length);
      if (nestedStart !== -1 && nestedStart < end) return false;
      remainder = `${remainder.slice(0, start)}${remainder.slice(end + endMarker.length)}`;
      removedBlock = true;
    }
  }

  return removedBlock && remainder.trim().length === 0;
}

/** Inspect one workspace without following a CLAUDE.md symlink. */
export function inspectLegacyClaudeInstruction(workspaceDir: string): LegacyInstructionInspection {
  const path = join(workspaceDir, LEGACY_CLAUDE_FILE);
  try {
    const stat = lstatSync(path);
    if (!stat.isFile() || stat.isSymbolicLink() || stat.size > MAX_INSTRUCTION_BYTES) {
      return { path, status: 'preserved' };
    }
    const content = readFileSync(path, 'utf8');
    return {
      path,
      status: isEntirelyAdeManagedInstruction(content) ? 'managed' : 'preserved',
    };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return { path, status: 'absent' };
    return { path, status: 'preserved' };
  }
}
