import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Page, Request } from 'playwright';
import type { mobileTlsProxy } from './mobileBrowser';

/** Real Electron, signed HTTPS browser and native Git; only fixture project code runs. */
export async function integrationFlow(desktop: Page, page: Page, root: string, evidence: string,
  proxy: Awaited<ReturnType<typeof mobileTlsProxy>>, check: (label: string, ok: boolean) => void) {
  for (const window of [desktop, page]) for (let i = 0; i < 5 && await window.locator('[role="dialog"],dialog[open]').count(); i++) await window.keyboard.press('Escape');
  await desktop.evaluate(async () => { for (const session of (await window.ade.invoke('pty:list')).sessions) if (session.status === 'running') await window.ade.invoke('pty:kill', { sessionId: session.id }); });
  const parent = join(root, 'integration-projects'); const target = join(parent, 'Integration UI'); const source = join(parent, 'old-palette'); mkdirSync(target, { recursive: true });
  const git = (cwd: string, ...args: string[]) => execFileSync('git', ['-C', cwd, '-c', 'user.name=UI fixture', '-c', 'user.email=fixture@localhost', '-c', 'commit.gpgSign=false', ...args], { encoding: 'utf8', windowsHide: true }).trim();
  git(target, 'init', '--initial-branch=main'); git(target, 'config', 'core.autocrlf', 'false');
  writeFileSync(join(target, 'package.json'), JSON.stringify({ scripts: { verify: 'node check.cjs' } }));
  writeFileSync(join(target, 'check.cjs'), 'if(!require("node:fs").readFileSync("part.txt","utf8").includes("palette"))process.exit(3);console.log("UI project passed");\n');
  writeFileSync(join(target, 'part.txt'), 'base\n'); git(target, 'add', '.'); git(target, 'commit', '-m', 'base');
  git(target, 'worktree', 'add', '-b', 'old-palette', source);
  writeFileSync(join(source, 'part.txt'), 'palette\n'); git(source, 'add', '.'); git(source, 'commit', '-m', 'palette');
  writeFileSync(join(source, 'AGENTS.md'), 'Source instructions remain local.\n');
  writeFileSync(join(target, 'newer.txt'), 'newer feature\n'); git(target, 'add', '.'); git(target, 'commit', '-m', 'newer feature');
  const oldHead = git(source, 'rev-parse', 'HEAD'); const targetHead = git(target, 'rev-parse', 'HEAD');
  const repo = await desktop.evaluate((path) => window.ade.invoke('repository:import', { path, name: 'Integration UI', executionBackend: 'native' }), target);
  const device = (await desktop.evaluate(() => window.ade.invoke('remoteDevices:list'))).devices.find((item) => item.name === 'Terminal tablet')!;
  await desktop.evaluate((deviceId) => window.ade.invoke('remoteDevices:setAdminScopes', { deviceId, scopes: ['workspace:read', 'workspace:write', 'repositories:write', 'projects:write', 'projectGit:write', 'terminal:control'], resourceAccess: { mode: 'all' } }), device.id);
  await desktop.reload(); await desktop.getByRole('tab', { name: 'Graph', exact: true }).click();
  await desktop.locator('button.grun-new', { hasText: 'Neuer Run' }).click();
  const runForm = desktop.locator('form.grun-modal'); await runForm.waitFor();
  await runForm.evaluate((node) => { node.dataset.integrationSubmits = '0'; node.addEventListener('submit', (event) => { event.preventDefault(); event.stopImmediatePropagation(); node.dataset.integrationSubmits = String(Number(node.dataset.integrationSubmits) + 1); }); });
  await runForm.locator('label.grun-field').filter({ has: desktop.getByText('Repository', { exact: true }) }).locator('select').selectOption(repo.id);
  await runForm.getByText('Git-Basis vor dem Run prüfen und aktualisieren', { exact: true }).click();
  await runForm.getByRole('button', { name: 'Änderungen übernehmen…', exact: true }).click();
  await runForm.getByLabel('Quell-Workspace', { exact: true }).locator('option', { hasText: 'old-palette' }).waitFor({ state: 'attached' });
  await runForm.getByRole('button', { name: 'Quellen und Berichte aktualisieren', exact: true }).click();
  await runForm.locator('.integration-review[aria-busy="false"]').waitFor();
  check('embedded integration actions never submit the surrounding run form', await runForm.getAttribute('data-integration-submits') === '0');
  await runForm.getByRole('button', { name: 'Zum Git-Abgleich', exact: true }).click();
  await desktop.waitForFunction(() => document.activeElement?.hasAttribute('data-open-integration'));
  check('return from integration restores the embedded Git opener', true);
  await runForm.getByTitle('Schließen', { exact: true }).click(); await runForm.waitFor({ state: 'hidden' });
  await desktop.locator('[data-open-git-sync]:visible').first().click();
  const sync = desktop.getByRole('dialog', { name: 'Repository synchronisieren', exact: true });
  await sync.getByLabel('Repository für Git-Abgleich', { exact: true }).selectOption(repo.id);
  await sync.getByRole('button', { name: 'Änderungen übernehmen…', exact: true }).click();
  const review = sync.getByRole('region', { name: 'Änderungen übernehmen', exact: true });
  const picker = review.getByLabel('Quell-Workspace', { exact: true }); await picker.locator('option', { hasText: 'old-palette' }).waitFor({ state: 'attached' });
  await picker.selectOption((await picker.locator('option', { hasText: 'old-palette' }).getAttribute('value'))!);
  await review.getByRole('button', { name: 'Änderungen prüfen', exact: true }).click();
  await review.getByLabel('Übernehmen: part.txt', { exact: true }).waitFor();
  check('integration progress names the current comparison step', await review.locator('[aria-current="step"]').innerText() === 'Dateien vergleichen');
  check('desktop preview focuses heading and excludes instructions by default', await review.getByRole('heading', { name: 'Änderungen geprüft übernehmen', exact: true }).evaluate((node) => node === document.activeElement)
    && await review.getByLabel('Übernehmen: part.txt', { exact: true }).isChecked() && !await review.getByLabel('Übernehmen: AGENTS.md', { exact: true }).isChecked());
  await review.getByRole('button', { name: 'Dateiauswahl leeren', exact: true }).click();
  check('empty integration selection prevents preparing a workspace', await review.getByRole('button', { name: 'Auswahl sichern und Arbeitskopie vorbereiten', exact: true }).isDisabled());
  await review.getByRole('button', { name: 'Empfohlene Auswahl wiederherstellen', exact: true }).click();
  check('restoring recommended selection keeps instructions excluded', await review.getByLabel('Übernehmen: part.txt', { exact: true }).isChecked()
    && !await review.getByLabel('Übernehmen: AGENTS.md', { exact: true }).isChecked());
  await review.getByRole('button', { name: 'Vergleich: part.txt', exact: true }).click();
  await review.getByRole('region', { name: 'Dateivergleich part.txt', exact: true }).getByText('palette', { exact: true }).waitFor();
  check('three-way text preview leaves source and target untouched', git(source, 'rev-parse', 'HEAD') === oldHead && git(target, 'rev-parse', 'HEAD') === targetHead);
  await desktop.screenshot({ path: join(evidence, 'integration-desktop-preview.png') });
  await review.getByRole('button', { name: 'Auswahl sichern und Arbeitskopie vorbereiten', exact: true }).click();
  const report = review.getByRole('region', { name: 'Übernahmebericht', exact: true }); await report.waitFor();
  check('desktop requires tests before final confirmation', await report.getByRole('button', { name: 'Geprüften Stand übernehmen', exact: true }).isDisabled());
  await report.getByRole('button', { name: 'Arbeitskopie öffnen', exact: true }).click(); await sync.waitFor({ state: 'hidden' });
  await desktop.getByRole('heading', { name: 'Projekt · Integration UI', exact: true }).waitFor();
  await desktop.getByRole('button', { name: 'Git', exact: true }).click();
  await desktop.getByRole('region', { name: 'Projekt-Git', exact: true }).getByText('part.txt', { exact: true }).first().waitFor();
  check('review copy opens in existing desktop project Git editor', true);

  const openMobile = async () => {
    await page.getByRole('tab', { name: 'Terminals', exact: true }).click();
    await page.getByRole('button', { name: 'Verwalten', exact: true }).click();
    const manager = page.getByRole('dialog', { name: 'Projekte und Agents verwalten', exact: true });
    await manager.getByRole('button', { name: 'Git-Abgleich', exact: true }).click();
    await manager.getByLabel('Verwaltetes Projekt', { exact: true }).selectOption(repo.id);
    await manager.getByRole('button', { name: 'Änderungen übernehmen…', exact: true }).click();
    return page.getByRole('dialog', { name: 'Änderungen übernehmen', exact: true });
  };
  await page.setViewportSize({ width: 1200, height: 900 }); await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  let dialog = await openMobile();
  await dialog.getByRole('button', { name: /old-palette · In Prüfung/ }).click();
  await dialog.getByRole('region', { name: 'Übernahmebericht', exact: true }).waitFor();
  check('mobile recovers the desktop-created review and takes focus', await dialog.getByRole('region', { name: 'Übernahmebericht', exact: true }).isVisible() && await dialog.evaluate((node) => node.contains(document.activeElement)));
  const keys: string[] = []; const requests = (request: Request) => { if (request.url().endsWith('/api/v1/integration/command')) keys.push(request.headers()['idempotency-key'] ?? ''); }; page.on('request', requests);
  proxy.loseIntegrationReplies(true); await dialog.getByRole('button', { name: 'Projektprüfungen starten', exact: true }).click();
  await dialog.getByRole('alert').waitFor(); proxy.loseIntegrationReplies(false);
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor(); dialog = await openMobile();
  await dialog.getByRole('button', { name: 'Anfrage erneut prüfen', exact: true }).click();
  await dialog.getByRole('status').filter({ hasText: /^Tests bestanden/ }).waitFor({ timeout: 90_000 });
  page.off('request', requests);
  check('mobile reload replays lost test acknowledgement with the same key', keys.length === 2 && !!keys[0] && keys[0] === keys[1]);
  await dialog.getByText('pnpm run verify · Bestanden', { exact: true }).click();
  await dialog.getByText('UI project passed', { exact: false }).waitFor();
  check('mobile displays real fixed-recipe project test output', true);
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: join(evidence, 'integration-phone-review.png') });
  check('review stays within phone width with keyboard reachable controls', await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth + 1 && node.getBoundingClientRect().right <= innerWidth));
  await dialog.getByLabel('Commit-Nachricht für Übernahme', { exact: true }).fill('feat: reviewed UI palette');
  await dialog.getByRole('checkbox', { name: /^Änderungen und erforderliche manuelle Prüfungen/ }).check();
  await dialog.getByRole('button', { name: 'Geprüften Stand übernehmen', exact: true }).click();
  await dialog.getByText('Übernommen als', { exact: false }).waitFor();
  check('explicit mobile confirmation fast-forwards tested source into newer main', readFileSync(join(target, 'part.txt'), 'utf8') === 'palette\n' && readFileSync(join(target, 'newer.txt'), 'utf8') === 'newer feature\n' && !git(target, 'status', '--porcelain'));
  check('completed transfer preserves source instructions and its original branch', git(source, 'rev-parse', 'HEAD') === oldHead && readFileSync(join(source, 'AGENTS.md'), 'utf8').includes('remain local'));
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  check('closing mobile review restores its manager opener', await page.getByRole('dialog', { name: 'Projekte und Agents verwalten', exact: true }).getByRole('button', { name: 'Änderungen übernehmen…', exact: true }).evaluate((node) => node === document.activeElement));
  await page.keyboard.press('Escape'); await page.setViewportSize({ width: 1400, height: 900 });
}
