import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Page, Locator } from 'playwright';
import type { mobileTlsProxy } from './mobileBrowser';

/** Real native Git and signed browser commands; no remote network or model calls. */
export async function projectGitFlow(desktop: Page, page: Page, root: string, evidence: string,
  proxy: Awaited<ReturnType<typeof mobileTlsProxy>>, check: (label: string, ok: boolean) => void) {
  const parent = join(root, 'git-projects'); const cwd = join(parent, 'Review project'); mkdirSync(cwd, { recursive: true });
  const gitAt = (path: string, ...args: string[]) => execFileSync('git', ['-C', path, '-c', 'commit.gpgSign=false', ...args], { encoding: 'utf8', windowsHide: true });
  const git = (...args: string[]) => gitAt(cwd, ...args); const write = (name: string, body: string) => writeFileSync(join(cwd, name), body);
  git('init', '--initial-branch=main'); git('config', 'core.autocrlf', 'false'); git('config', 'user.name', 'UI fixture'); git('config', 'user.email', 'fixture@example.invalid');
  write('a.txt', 'base\n'); write('b.txt', 'base\n'); git('add', '.'); git('commit', '-m', 'base'); write('a.txt', 'selected edit\n'); write('b.txt', 'staged elsewhere\n'); git('add', 'b.txt');
  await desktop.evaluate((rootPath) => window.ade.invoke('projectDefaults:save', { rootPath, agentId: null }), parent);
  const device = (await desktop.evaluate(() => window.ade.invoke('remoteDevices:list'))).devices.find((item) => item.name === 'Terminal tablet')!;
  const grants = [...new Set([...(device.adminScopes ?? []), 'projects:write' as const])];
  await desktop.evaluate(({ deviceId, scopes }) => window.ade.invoke('remoteDevices:setAdminScopes', { deviceId, scopes }), { deviceId: device.id, scopes: grants });
  await desktop.keyboard.press('Escape'); await desktop.getByRole('tab', { name: 'Projekte view', exact: true }).click();
  await desktop.getByRole('button', { name: 'Workspace öffnen: Review project', exact: true }).click();
  await desktop.getByRole('button', { name: 'Git', exact: true }).click();
  const desktopGit = desktop.getByRole('region', { name: 'Projekt-Git', exact: true });
  await desktopGit.getByLabel('a.txt', { exact: true }).check(); await desktopGit.getByLabel('Commit-Nachricht', { exact: true }).fill('Review selected edit');
  await desktopGit.getByRole('button', { name: 'Diff anzeigen: a.txt', exact: true }).click();
  await desktopGit.getByRole('region', { name: 'Git-Diff', exact: true }).getByText('+selected edit', { exact: false }).waitFor();
  const oldHead = git('rev-parse', 'HEAD'); await desktopGit.getByRole('button', { name: 'Commit prüfen', exact: true }).click();
  const review = desktopGit.getByRole('region', { name: 'Git-Vorschau', exact: true });
  check('desktop Git preview takes focus and lists only selected file before commit', await review.evaluate((node) => node.contains(document.activeElement))
    && await review.getByText('a.txt', { exact: true }).isVisible() && !await review.getByText('b.txt', { exact: true }).count() && git('rev-parse', 'HEAD') === oldHead);
  await review.getByRole('button', { name: 'Abbrechen', exact: true }).click();
  check('cancelled Git preview returns focus to stable Git heading', await desktopGit.getByRole('heading', { name: 'Git · main', exact: true }).evaluate((node) => node === document.activeElement));
  await desktopGit.getByRole('button', { name: 'Commit prüfen', exact: true }).click(); await review.waitFor(); await desktop.screenshot({ path: join(evidence, 'project-git-commit.png') });
  await review.getByRole('button', { name: 'Git-Aktion ausführen', exact: true }).click();
  await desktopGit.getByText('Git-Aktion bestätigt.', { exact: false }).waitFor();
  check('desktop selective commit preserves unrelated staged changes', git('show', 'HEAD:a.txt') === 'selected edit\n' && git('show', 'HEAD:b.txt') === 'base\n' && git('diff', '--cached', '--name-only').trim() === 'b.txt');
  await page.keyboard.press('Escape'); await page.getByRole('tab', { name: 'Projekte', exact: true }).click();
  await page.getByRole('button', { name: 'Workspace öffnen: Review project', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Projekt · Review project', exact: true }); await dialog.getByRole('button', { name: 'Workspace öffnen', exact: true }).click();
  await dialog.getByRole('button', { name: 'Git', exact: true }).click(); const panel = dialog.getByRole('region', { name: 'Projekt-Git', exact: true });
  await panel.getByLabel('b.txt', { exact: true }).check(); await panel.getByLabel('Commit-Nachricht', { exact: true }).fill('Tablet commit');
  check('tablet Git requires explicit mutation grant', await panel.getByRole('button', { name: 'Commit prüfen', exact: true }).isDisabled());
  await desktop.evaluate(({ deviceId, scopes }) => window.ade.invoke('remoteDevices:setAdminScopes', { deviceId, scopes }), { deviceId: device.id, scopes: [...grants, 'projectGit:write' as const, 'workspace:write' as const] });
  await dialog.getByRole('button', { name: 'Workspace aktualisieren', exact: true }).click();
  await panel.getByRole('button', { name: 'Commit prüfen', exact: true }).click();
  const confirm = async (area: Locator) => { await area.getByRole('region', { name: 'Git-Vorschau', exact: true }).getByRole('button', { name: 'Git-Aktion ausführen', exact: true }).click(); await area.getByRole('region', { name: 'Git-Vorschau', exact: true }).waitFor({ state: 'hidden' }); };
  proxy.loseProjectReplies(true); await panel.getByRole('button', { name: 'Git-Aktion ausführen', exact: true }).click();
  await panel.getByRole('alert').waitFor(); proxy.loseProjectReplies(false); const committedCount = git('rev-list', '--count', 'HEAD');
  check('lost Git reply follows a real successful commit', git('show', 'HEAD:b.txt') === 'staged elsewhere\n');
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await panel.getByRole('button', { name: 'Git-Aktion erneut prüfen', exact: true }).click();
  await panel.getByText('Arbeitsverzeichnis sauber', { exact: false }).waitFor();
  check('reload and explicit receipt replay create no duplicate commit', git('rev-list', '--count', 'HEAD') === committedCount);
  git('switch', '-c', 'feature/tablet-review'); write('a.txt', 'feature side\n'); git('add', 'a.txt'); git('commit', '-m', 'feature'); git('switch', 'main'); write('a.txt', 'main side\n'); git('add', 'a.txt'); git('commit', '-m', 'main side');
  await panel.getByRole('button', { name: 'Git aktualisieren', exact: true }).click();
  await panel.getByText('Branches zusammenführen und Remote-Stand', { exact: true }).click(); await panel.getByLabel('Git-Quellbranch', { exact: true }).selectOption('refs/heads/feature/tablet-review');
  await panel.getByRole('button', { name: 'Merge prüfen', exact: true }).click(); await confirm(panel);
  await panel.getByText('Merge offen · 1 Konfliktdateien', { exact: true }).waitFor();
  check('tablet exposes real merge conflict instead of reporting success', git('ls-files', '-u').includes('a.txt') && await panel.getByRole('button', { name: 'Merge abschliessen prüfen', exact: true }).isDisabled());
  await page.screenshot({ path: join(evidence, 'project-git-conflict.png') });
  await panel.getByRole('button', { name: 'Datei bearbeiten: a.txt', exact: true }).click(); const editor = panel.getByLabel('Git-Dateiinhalt', { exact: true });
  await editor.waitFor(); check('conflict editor receives focus with actual marker text', await editor.evaluate((node) => node === document.activeElement) && (await editor.inputValue()).includes('<<<<<<<'));
  await editor.fill('combined from tablet\n'); proxy.loseWorkspaceReplies(true);
  await panel.getByRole('button', { name: 'Datei speichern', exact: true }).click(); await panel.getByRole('alert').waitFor(); proxy.loseWorkspaceReplies(false);
  check('lost file reply leaves exact resolution on disk', readFileSync(join(cwd, 'a.txt'), 'utf8') === 'combined from tablet\n');
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await panel.getByRole('button', { name: 'Dateispeicherung erneut prüfen', exact: true }).click();
  await panel.getByRole('region', { name: 'Git-Datei', exact: true }).waitFor({ state: 'hidden' });
  check('reload recovers exact pending conflict save without overwriting another version', readFileSync(join(cwd, 'a.txt'), 'utf8') === 'combined from tablet\n');
  await panel.getByLabel('a.txt', { exact: true }).check(); await panel.getByRole('button', { name: 'Als aufgelöst prüfen', exact: true }).click(); await confirm(panel);
  await panel.getByRole('button', { name: 'Merge abschliessen prüfen', exact: true }).click(); await confirm(panel); await panel.getByText('Arbeitsverzeichnis sauber', { exact: false }).waitFor();
  check('tablet finishes merge with real two-parent commit', git('rev-list', '--parents', '-n', '1', 'HEAD').trim().split(' ').length === 3 && git('show', 'HEAD:a.txt') === 'combined from tablet\n');
  git('switch', 'feature/tablet-review'); write('a.txt', 'feature again\n'); git('add', 'a.txt'); git('commit', '-m', 'again'); git('switch', 'main'); const beforeAbort = git('rev-parse', 'HEAD');
  await panel.getByRole('button', { name: 'Git aktualisieren', exact: true }).click(); await panel.getByText('Branches zusammenführen und Remote-Stand', { exact: true }).click();
  await panel.getByLabel('Git-Quellbranch', { exact: true }).selectOption('refs/heads/feature/tablet-review'); await panel.getByRole('button', { name: 'Merge prüfen', exact: true }).click(); await confirm(panel);
  await panel.getByRole('button', { name: 'Merge abbrechen prüfen', exact: true }).click();
  await panel.getByRole('region', { name: 'Git-Vorschau', exact: true }).waitFor();
  check('abort preview explains discarded merge resolution before mutation', await panel.getByText('Abbrechen verwirft', { exact: false }).isVisible() && existsSync(join(cwd, '.git', 'MERGE_HEAD')));
  await confirm(panel); check('tablet abort restores original HEAD', git('rev-parse', 'HEAD') === beforeAbort && !existsSync(join(cwd, '.git', 'MERGE_HEAD')));
  const remote = join(root, 'git-ui-remote.git'); const peer = join(root, 'git-ui-peer'); mkdirSync(remote); gitAt(remote, 'init', '--bare'); git('remote', 'add', 'origin', remote); git('push', 'origin', 'main'); gitAt(root, 'clone', '--branch', 'main', remote, peer);
  gitAt(peer, 'config', 'user.name', 'UI fixture'); gitAt(peer, 'config', 'user.email', 'fixture@example.invalid'); writeFileSync(join(peer, 'remote.txt'), 'remote\n'); gitAt(peer, 'add', 'remote.txt'); gitAt(peer, 'commit', '-m', 'remote update'); gitAt(peer, 'push', 'origin', 'main');
  await panel.getByRole('button', { name: 'Git aktualisieren', exact: true }).click(); await panel.getByText('Branches zusammenführen und Remote-Stand', { exact: true }).click();
  await panel.getByRole('button', { name: 'Fetch prüfen', exact: true }).click(); await confirm(panel);
  await panel.getByText('Branches zusammenführen und Remote-Stand', { exact: true }).click(); await panel.getByRole('button', { name: 'Fast-forward prüfen', exact: true }).click(); await confirm(panel);
  check('tablet fetch and reviewed fast-forward bring exact remote commit', git('rev-parse', 'HEAD') === gitAt(peer, 'rev-parse', 'HEAD') && existsSync(join(cwd, 'remote.txt')));
  await page.setViewportSize({ width: 390, height: 844 }); check('Git controls fit phone width', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: join(evidence, 'project-git-phone.png') });
  check('final browser positive control leaves clean main and preserved resolution', !git('status', '--porcelain').trim() && git('branch', '--show-current').trim() === 'main' && git('show', 'HEAD:a.txt') === 'combined from tablet\n');
}
