import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { ConfigStore } from '../src/main/config/store';
import { ProjectDefaultsService } from '../src/main/settings/ProjectDefaultsService';
import { ProjectWorkspaceService } from '../src/main/repositories/ProjectWorkspaceService';
import { terminalWorkspaceBranch } from '../src/main/repositories/TerminalWorkspaceIdentity';

let passed = 0; let failed = 0;
const check = (name: string, ok: boolean) => { if (!ok) throw new Error(name); passed++; console.log(`  ok ${name}`); };
const refuses = async (name: string, fn: () => unknown, reason: RegExp) => { try { await fn(); } catch (error) { check(name, reason.test(String(error))); return; } throw new Error(name); };
const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-terminal-identity-')));
void (async () => {
  const main = join(root, 'Original'); mkdirSync(main);
  const git = (...args: string[]) => execFileSync('git', ['-C', main, '-c', 'core.fsmonitor=false', '-c', 'user.name=Fixture', '-c', 'user.email=fixture@localhost', '-c', 'commit.gpgSign=false', ...args], { encoding: 'utf8', windowsHide: true }).trim();
  git('init', '--initial-branch=main'); git('commit', '--allow-empty', '-m', 'fixture');
  const store = new ConfigStore(join(root, 'profile', 'config.json'));
  new ProjectDefaultsService(store).save({ rootPath: root, agentId: null });
  const service = new ProjectWorkspaceService(store);
  const view = await service.open((await service.directory()).entries.find(item => item.name === 'Original')!.id);
  const original = await service.resolve(view.id);
  const fullResolve = service.resolve.bind(service); let fullProbes = 0;
  service.resolve = async id => { fullProbes++; return fullResolve(id); };
  check('original terminal uses recorded checkout and actual branch', (await service.resolveTerminal(view.id)).branch === 'main' && fullProbes === 0);
  git('switch', '-c', 'feature/änderung');
  check('external branch switch is observed on next call without cached authority', (await service.resolveTerminal(view.id)).branch === 'feature/änderung');
  git('switch', '--detach');
  check('detached HEAD is explicit', (await service.resolveTerminal(view.id)).branch === '(detached HEAD)');
  git('switch', 'main'); git('pack-refs', '--all');
  check('packed branch refs do not require Git process probes', (await service.resolveTerminal(view.id)).branch === 'main' && fullProbes === 0);
  const work = join(root, 'Parallel'); git('worktree', 'add', '-b', 'task/parallel', work);
  const branch = await service.registerCheckout(work, view.repositoryId, () => undefined);
  const tree = (await service.resolveTerminal(branch.id)).workspace;
  check('parallel terminal validates commondir and backlink and retains own branch', (await service.resolveTerminal(branch.id)).branch === 'task/parallel' && fullProbes === 0);
  const commonFile = join(tree.gitDirectory, 'commondir'); const common = readFileSync(commonFile);
  writeFileSync(commonFile, '../../elsewhere');
  await refuses('commondir retarget is rejected before terminal I/O', () => service.resolveTerminal(branch.id), /Git-Zuordnung/);
  writeFileSync(commonFile, common);
  const backFile = join(tree.gitDirectory, 'gitdir'); const back = readFileSync(backFile);
  writeFileSync(backFile, join(root, 'Other', '.git'));
  await refuses('worktree backlink retarget is rejected', () => service.resolveTerminal(branch.id), /Git-Zuordnung/);
  writeFileSync(backFile, back);
  const headFile = join(tree.gitDirectory, 'HEAD'); const head = readFileSync(headFile);
  writeFileSync(headFile, 'x'.repeat(4097));
  await refuses('oversized HEAD is bounded', () => service.resolveTerminal(branch.id), /Metadaten/);
  writeFileSync(headFile, head);
  renameSync(headFile, `${headFile}.saved`);
  const outside = join(root, 'outside-head'); writeFileSync(outside, head);
  symlinkSync(outside, headFile, 'file');
  await refuses('HEAD symlink is refused rather than read outside workspace', () => service.resolveTerminal(branch.id), /Verknüpfung|Umleitung/);
  rmSync(headFile); renameSync(`${headFile}.saved`, headFile);
  const pointer = join(work, '.git'); const pointerText = readFileSync(pointer);
  rmSync(pointer);
  writeFileSync(pointer, `gitdir: ${join(root, 'other')}\n`);
  await refuses('changed worktree pointer invalidates recorded identity', () => service.resolveTerminal(branch.id), /verschoben|ersetzt/);
  rmSync(pointer); writeFileSync(pointer, pointerText);
  // Restore through the full registration service, never by weakening the stored stamp.
  store.save({ projectWorkspaces: store.get().projectWorkspaces.filter(item => item.id !== branch.id) });
  const repaired = await service.registerCheckout(work, view.repositoryId, () => undefined);
  check('positive control restores correct parallel scope after pointer rejection', (await service.resolveTerminal(repaired.id)).branch === 'task/parallel');
  const displaced = join(root, 'Original.saved'); renameSync(main, displaced); mkdirSync(main);
  await refuses('replacement original directory cannot inherit the terminal identity', () => service.resolveTerminal(view.id), /verschoben|ersetzt/);
  rmdirSync(main); renameSync(displaced, main);
  const repositories = store.get().repositories;
  store.save({ repositories: repositories.map(item => ({ ...item, verified: false })) });
  await refuses('unverified project is rejected immediately', () => service.resolveTerminal(view.id), /nicht verfügbar/);
  store.save({ repositories });
  const ref = join(main, '.git', 'refs', 'heads', 'alias'); mkdirSync(join(main, '.git', 'refs', 'heads'), { recursive: true });
  writeFileSync(ref, 'ref: refs/heads/main\n'); writeFileSync(join(main, '.git', 'HEAD'), 'ref: refs/heads/alias\n');
  check('HEAD symbolic-ref chains fall back to full Git semantics', (await service.resolveTerminal(view.id)).branch === 'main' && fullProbes === 1);
  writeFileSync(join(main, '.git', 'HEAD'), 'ref: refs/heads/main\n');
  check('uncommon separate Git directory requests full resolver', terminalWorkspaceBranch(original.workspace, { ...original.repository, commonGitDir: join(root, 'separate') }) === null);
  check('final positive original scope remains unchanged and usable', (await service.resolveTerminal(view.id)).branch === 'main' && git('status', '--porcelain') === '');
})().catch(error => { failed++; console.error(error); }).finally(() => {
  const target = resolve(root); const parent = resolve(tmpdir());
  if (target.startsWith(parent + '\\') || target.startsWith(parent + '/')) rmSync(target, { recursive: true, force: true });
  console.log(`Terminal workspace identity: ${passed} passed, ${failed} failed`); process.exitCode = failed ? 1 : 0;
});
