import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync, linkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createRemoteWorkspaceFixture } from './helpers/remoteWorkspaceFixture';
import { RemoteApiError, type RemoteCommandContext } from '../src/main/application/AdeApplicationService';

let passed = 0;
const check = (name: string, ok: boolean) => { if (!ok) throw new Error(name); passed++; console.log(`  ok  ${name}`); };
async function refuses(name: string, action: () => unknown, code: string) {
  try { await action(); } catch (error) { check(name, error instanceof RemoteApiError && error.code === code); return; }
  throw new Error(name);
}
const root = mkdtempSync(join(tmpdir(), 'ade-remote-commits-'));
void (async () => {
  const fixture = createRemoteWorkspaceFixture(root); const { application: app, devices, store } = fixture;
  devices.enroll('tablet', 'Tablet', 'd'.repeat(40)); devices.setAdminScopes('tablet', ['catalog:write', 'workspace:read']);
  const context = (): RemoteCommandContext => ({ principal: { id: 'tablet', kind: 'device', proof: 'device-signature', scopes: new Set(devices.activeDevices()[0]!.scopes) }, idempotencyKey: randomUUID(), requestId: 'commit-detail' });
  const repositoryId = (await app.administer(context(), { operation: 'project-create', input: { name: 'Commit details' } })).created!.id;
  const selection = { agentId: 'builder', repositoryId };
  await app.administer(context(), { operation: 'workspace-prepare', input: selection });
  const binding = store.get().workspaceBindings.find((item) => item.repositoryId === repositoryId)!;
  const cwd = binding.workspaceDir;
  const git = (...args: string[]) => execFileSync('git', ['-C', cwd, '-c', 'user.name=Commit Author', '-c', 'user.email=author@example.test', '-c', 'commit.gpgSign=false', ...args], { encoding: 'utf8', windowsHide: true });
  const query = (input: Record<string, unknown>, ctx = context()) => app.queryWorkspace(ctx, { ...selection, ...input });
  const details = async (sha: string) => (await query({ operation: 'commit', sha })).commit!;
  const commit = (message: string) => { git('add', '-A'); git('commit', '-m', message); return git('rev-parse', 'HEAD').trim(); };
  const initial = git('rev-parse', 'HEAD').trim();
  check('empty root commit has an explicit empty comparison', (await details(initial)).parents.length === 0 && (await details(initial)).files.length === 0);
  writeFileSync(join(cwd, 'a.txt'), 'old\nkeep\n'); commit('Base');
  writeFileSync(join(cwd, 'a.txt'), 'new\nkeep\nextra\n');
  writeFileSync(join(cwd, '.env'), 'SECRET=never-expose');
  writeFileSync(join(cwd, 'binary.dat'), Buffer.from([0, 1, 2]));
  writeFileSync(join(cwd, 'Grüsse.txt'), 'Hallo\n');
  const sha = commit('Improve layout\n\nFull explanation of the layout change.');
  const detail = await details(sha);
  check('metadata includes full message, author and both ISO timestamps', detail.sha === sha && detail.author === 'Commit Author' && detail.message.includes('Full explanation') && Number.isFinite(Date.parse(detail.authoredAt)) && Number.isFinite(Date.parse(detail.committedAt)));
  check('line totals are exact for visible text files', detail.additions === 3 && detail.deletions === 1 && detail.binaryFiles === 1);
  check('protected files never appear and totals are labelled partial', detail.limited && !JSON.stringify(detail).includes('.env') && detail.files.length === 3);
  check('unicode filenames survive nul-delimited Git parsing', detail.files.some((file) => file.path === 'Grüsse.txt'));
  check('modified files carry their status and per-file statistics', detail.files.some((file) => file.path === 'a.txt' && file.status === 'modified' && file.additions === 2 && file.deletions === 1));
  const patch = await query({ operation: 'commit-file', sha, path: 'a.txt' });
  check('selected commit patch contains added and deleted lines', patch.diff!.includes('+new') && patch.diff!.includes('-old') && !patch.limited);
  writeFileSync(join(cwd, 'a.txt'), 'uncommitted unrelated text\n');
  check('historical patch is independent of the dirty working file', (await query({ operation: 'commit-file', sha, path: 'a.txt' })).diff === patch.diff);
  const binary = await query({ operation: 'commit-file', sha, path: 'binary.dat' });
  check('binary changes have a useful notice without fabricated line counts', binary.diff === '' && binary.notice!.includes('Binärdatei') && detail.files.find((file) => file.path === 'binary.dat')!.additions === null);
  await refuses('protected historical paths cannot be opened directly', () => query({ operation: 'commit-file', sha, path: '.env' }), 'command_rejected');
  await refuses('unchanged paths cannot be read through the commit patch API', () => query({ operation: 'commit-file', sha, path: 'not-changed.txt' }), 'command_rejected');
  for (const invalid of ['HEAD', '--all', 'a'.repeat(41), `${sha}^`, 'b'.repeat(39)]) await refuses('reject noncanonical commit reference', () => query({ operation: 'commit', sha: invalid }), 'invalid_payload');
  await refuses('commit queries reject injected host fields', () => query({ operation: 'commit', sha, cwd }), 'invalid_payload');
  await refuses('commit queries reject a home-only selection', () => app.queryWorkspace(context(), { agentId: 'builder', repositoryId: null, operation: 'commit', sha }), 'command_rejected');
  git('checkout', '--', 'a.txt');
  const rootWithFiles = git('commit-tree', `${sha}^{tree}`, '-m', 'Root with files').trim();
  git('switch', '-c', 'root-with-files', rootWithFiles);
  check('root commits compare real file additions against an empty tree', (await details(rootWithFiles)).files.some((file) => file.path === 'a.txt' && file.status === 'added' && file.additions === 3));
  git('switch', binding.branch);
  git('switch', '-c', 'other-history'); writeFileSync(join(cwd, 'other.txt'), 'other branch only\n'); const other = commit('Other history'); git('switch', binding.branch);
  await refuses('object ids outside the selected branch history are refused', () => details(other), 'command_rejected');
  writeFileSync(join(cwd, 'ours.txt'), 'ours\n'); commit('Ours'); git('merge', '--no-ff', '-m', 'Merge fixture', 'other-history');
  const merge = await details(git('rev-parse', 'HEAD').trim());
  check('merge comparison uses first parent and only incoming changes', merge.parents.length === 2 && merge.files.length === 1 && merge.files[0]!.path === 'other.txt' && merge.additions === 1);
  rmSync(join(cwd, 'Grüsse.txt')); const deleted = commit('Remove file');
  check('deleted files remain inspectable from immutable history', (await details(deleted)).files[0]!.status === 'deleted' && (await query({ operation: 'commit-file', sha: deleted, path: 'Grüsse.txt' })).diff!.includes('-Hallo'));
  writeFileSync(join(cwd, 'large.txt'), Array.from({ length: 8000 }, (_, index) => `line ${index}`).join('\n') + '\n'); const large = commit('Long patch');
  const largePatch = await query({ operation: 'commit-file', sha: large, path: 'large.txt' });
  check('long patches are explicitly capped while full line counts remain exact', largePatch.limited === true && largePatch.diff!.length < 66000 && (await details(large)).additions === 8000);
  writeFileSync(join(cwd, 'private-path.txt'), 'api_key=private-value\nC:\\private\\source\n'); const redacted = commit('Redacted body\n\nC:\\private\\source');
  const redactedWire = JSON.stringify([await details(redacted), await query({ operation: 'commit-file', sha: redacted, path: 'private-path.txt' })]);
  check('commit messages and patches use wire redaction', !redactedWire.includes('private-value') && !redactedWire.includes('C:') && !redactedWire.includes(root));
  linkSync(join(cwd, 'a.txt'), join(cwd, 'hardlinked.txt')); const linked = commit('Linked file');
  check('current hardlinks cannot become historical browsing entry points', !(await details(linked)).files.some((file) => file.path === 'hardlinked.txt'));
  const blob = execFileSync('git', ['-C', cwd, 'hash-object', '-w', '--stdin'], { input: '/outside/private', encoding: 'utf8', windowsHide: true }).trim();
  git('update-index', '--add', '--cacheinfo', `120000,${blob},historical-link`); git('commit', '-m', 'Historical symlink');
  check('historical symlink targets are omitted even without a current filesystem link', (await details(git('rev-parse', 'HEAD').trim())).files.length === 0);
  git('reset', '--', 'historical-link');
  for (let index = 0; index < 501; index++) writeFileSync(join(cwd, `bounded-${index}.txt`), 'one\n');
  const bounded = await details(commit('Bounded file list'));
  check('large commit file lists and their visible totals stop at 500', bounded.limited && bounded.files.length === 500 && bounded.additions === 500);
  const stale = context(); devices.setAdminScopes('tablet', ['catalog:write']);
  await refuses('revoked read grant cannot read historical metadata', () => query({ operation: 'commit', sha }, stale), 'scope_not_granted');
  devices.setAdminScopes('tablet', ['catalog:write', 'workspace:read']);
  check('final positive control still reads the original commit after restoring access', (await details(sha)).sha === sha);
  fixture.workbench.dispose();
  console.log(`Remote commits: ${passed} passed, 0 failed`);
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => rmSync(root, { recursive: true, force: true }));
