import { mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { chromium, type Browser } from 'playwright';
import { projectPublishFixture } from './helpers/projectPublishFixture';
import { mobileTlsProxy } from './helpers/mobileBrowser';
import { BrowserSessions } from '../src/main/remote/BrowserSessions';
import { HostApiServer } from '../src/main/remote/HostApiServer';
import { RemoteAuthorizer } from '../src/main/remote/authorization';
import { loadMobileAssets } from '../src/main/remote/mobileAssets';
let passed = 0; let failed = 0;
const check = (name: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${name}`); } else { failed++; console.error(`FAIL  ${name}`); } };
const root = mkdtempSync(join(tmpdir(), 'ade-publish-browser-')); const evidence = resolve('test-results/remote'); mkdirSync(evidence, { recursive: true });
let browser: Browser | undefined; let server: HostApiServer | undefined; let proxy: Awaited<ReturnType<typeof mobileTlsProxy>> | undefined; let sessions: BrowserSessions | undefined;
void (async () => {
  const f = projectPublishFixture(root); const setup = await f.setup();
  proxy = await mobileTlsProxy(); sessions = new BrowserSessions(f.devices);
  server = new HostApiServer(f.application, { port: 0, heartbeatMs: 200, requireDeviceReads: true,
    authorizer: new RemoteAuthorizer('t'.repeat(32), [], undefined, f.devices), browser: { origin: proxy.origin, sessions, assets: loadMobileAssets(resolve('out/mobile')) }, audit: (entry) => f.devices.audit(entry) });
  proxy.target((await server.start()).port);
  browser = await chromium.launch({ args: ['--ignore-certificate-errors', '--host-resolver-rules=MAP ade-mobile.fixture.ts.net 127.0.0.1'] });
  const page = await browser.newPage({ viewport: { width: 1024, height: 768 }, hasTouch: true, ignoreHTTPSErrors: true }); page.setDefaultTimeout(45_000);
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(sessions.beginPairing(proxy.origin).url); await page.getByRole('button', { name: 'Dieses Gerät verbinden', exact: true }).click();
  await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor(); const device = f.devices.activeDevices()[0]!;
  f.devices.setAdminScopes(device.id, ['workspace:read', 'projects:write', 'projectGit:write']);
  await page.getByRole('tab', { name: 'Projekte', exact: true }).click(); await page.getByRole('button', { name: 'Workspace öffnen: Publication demo', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Projekt · Publication demo', exact: true });
  await dialog.getByRole('button', { name: 'Workspace öffnen', exact: true }).click(); await dialog.getByRole('button', { name: 'Git', exact: true }).click();
  await dialog.getByText('Push und Pull Request', { exact: true }).click(); const panel = dialog.getByRole('region', { name: 'Projekt veröffentlichen', exact: true });
  await panel.getByRole('button', { name: 'Remote-Stand prüfen', exact: true }).click();
  await panel.getByText('Branch noch nicht vorhanden', { exact: false }).waitFor();
  check('signed tablet can inspect target but local Git grant cannot push', await panel.getByRole('button', { name: 'Push prüfen', exact: true }).isDisabled());
  f.devices.setAdminScopes(device.id, ['workspace:read', 'projects:write', 'projectGit:write', 'projectGit:publish']);
  await dialog.getByRole('button', { name: 'Workspace aktualisieren', exact: true }).click();
  const review = panel.getByRole('region', { name: 'Veröffentlichungsvorschau', exact: true });
  await panel.getByRole('button', { name: 'Push prüfen', exact: true }).click(); await review.waitFor();
  check('push review takes focus with exact branch and commit before remote mutation', await review.evaluate((node) => node.contains(document.activeElement))
    && (await review.innerText()).includes(setup.run('rev-parse', '--short=12', 'HEAD')) && !f.runAt(f.remote, 'show-ref', '--heads').includes('feature/review'));
  await review.getByRole('button', { name: 'Abbrechen', exact: true }).click();
  check('publication cancel returns focus to stable publisher summary when opener unmounts', await dialog.getByText('Push und Pull Request', { exact: true }).evaluate((node) => node === document.activeElement));
  await panel.getByRole('button', { name: 'Push prüfen', exact: true }).click(); await review.waitFor(); await review.scrollIntoViewIfNeeded(); await page.screenshot({ path: join(evidence, 'project-push-preview.png') });
  proxy.loseProjectReplies(true); await review.getByRole('button', { name: 'Push ausführen', exact: true }).click(); await panel.getByRole('alert').waitFor(); proxy.loseProjectReplies(false);
  check('lost push reply follows exact real bare-remote update', f.runAt(f.remote, 'rev-parse', 'feature/review') === setup.run('rev-parse', 'HEAD'));
  const pushes = f.gitCalls.filter((args) => args.includes('push')).length;
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await review.getByRole('button', { name: 'Veröffentlichung erneut prüfen', exact: true }).click(); await panel.getByText('Push bestätigt', { exact: false }).waitFor();
  check('reload replays push receipt without another external write', f.gitCalls.filter((args) => args.includes('push')).length === pushes);
  setup.useGitHub(); await panel.getByRole('button', { name: 'Remote-Stand prüfen', exact: true }).click(); await panel.getByText('Dieser Commit ist auf dem Remote.', { exact: true }).waitFor();
  await panel.getByText('GitHub Pull Request vorbereiten', { exact: true }).click();
  await panel.getByLabel('PR-Titel', { exact: true }).fill('Review tablet delivery'); await panel.getByLabel('PR-Beschreibung', { exact: true }).fill('Files checked on the tablet.\n\nValidation: isolated Git fixture.');
  await panel.getByRole('button', { name: 'PR prüfen', exact: true }).click(); await review.waitFor();
  check('PR review includes provider source target full body and draft choice', (await review.innerText()).includes('github.com/ade-fixture/review · feature/review → main') && (await review.innerText()).includes('Validation: isolated Git fixture.') && (await review.innerText()).includes('PR als Entwurf'));
  await review.scrollIntoViewIfNeeded(); await page.screenshot({ path: join(evidence, 'project-pr-preview.png') });
  proxy.loseProjectReplies(true); await review.getByRole('button', { name: 'PR erstellen', exact: true }).click(); await panel.getByRole('alert').waitFor(); proxy.loseProjectReplies(false);
  check('lost PR reply leaves one provider creation with exact user body', f.controls.prCount === 1 && f.ghCalls.find((call) => call.args[1] === 'create')?.input?.includes('\n\nValidation:') === true);
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await review.getByRole('button', { name: 'Veröffentlichung erneut prüfen', exact: true }).click(); await panel.getByRole('link', { name: 'PR öffnen', exact: true }).waitFor();
  check('PR receipt replay gives safe exact link without duplicate or implicit push', await panel.getByRole('link', { name: 'PR öffnen', exact: true }).getAttribute('href') === 'https://github.com/ade-fixture/review/pull/1'
    && f.controls.prCount === 1 && f.gitCalls.filter((args) => args.includes('push')).length === pushes);
  await panel.getByRole('button', { name: 'Remote-Stand prüfen', exact: true }).click(); await panel.getByRole('link', { name: 'PR #1', exact: true }).waitFor();
  check('explicit remote inspection exposes existing PR and current commit', await panel.getByText('Dieser Commit ist auf dem Remote.', { exact: true }).isVisible());
  await page.context().setOffline(true); await page.getByRole('status').filter({ hasText: /^Offline$/ }).waitFor();
  check('offline publication keeps current details and disables commands', await panel.getByRole('button', { name: 'Push prüfen', exact: true }).isDisabled());
  await page.context().setOffline(false); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 }); await panel.scrollIntoViewIfNeeded();
  check('publication fields and preview fit phone width', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: join(evidence, 'project-publish-phone.png') });
  check('final signed-browser positive control preserves clean exact branch without page errors', !setup.run('status', '--porcelain') && f.controls.prCount === 1 && errors.length === 0);
})().catch((error) => { failed++; console.error(error); }).finally(async () => {
  await browser?.close(); await server?.stop(); sessions?.dispose(); await proxy?.close();
  if (dirname(resolve(root)) !== resolve(tmpdir())) throw new Error('unexpected fixture root'); rmSync(root, { recursive: true, force: true });
  console.log(`Project publication browser: ${passed} passed, ${failed} failed`); process.exitCode = failed ? 1 : 0;
});
