/** Actual renderer/preload/main/store with isolated native protocol peer. No paid model calls. */
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { _electron as electron, type ElectronApplication, type Page } from 'playwright';
import { expect } from 'playwright/test';
import { COORDINATOR_DISABLED_FEATURES } from '../src/main/pty/CoordinatorCodexPolicy';
import { createServer } from 'node:net';
import { conversationMobileFlow } from './helpers/conversationMobileFlow';
import { conversationVoiceFlow } from './helpers/conversationVoiceFlow';
import { coordinatorActionsFlow } from './helpers/coordinatorActionsFlow';
const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-conversation-electron-')));
const evidence = resolve('test-results/main-agent-planning'); mkdirSync(evidence, { recursive: true });
let passed = 0; let failed = 0; let app: ElectronApplication | undefined;
const check = (label: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${label}`); } else { failed++; console.error(`FAIL  ${label}`); } };
async function main() {
  const reservation = createServer(); await new Promise<void>(done => reservation.listen(0, '127.0.0.1', done));
  const address = reservation.address(); if (!address || typeof address === 'string') throw new Error('Missing fixture port');
  const port = address.port; await new Promise<void>(done => reservation.close(() => done()));
  const launcher = join(root, 'launch.cjs');
  const config = { features: { ...Object.fromEntries(COORDINATOR_DISABLED_FEATURES.map(name => [name, false])), code_mode_host: true }, mcp_servers: {}, agents: { enabled: false }, web_search: 'disabled', sandbox_mode: 'read-only', approval_policy: 'never' };
  writeFileSync(launcher, `require(${JSON.stringify(resolve('scripts/fixtures/conversation-speech.cjs'))});
const cp=require('node:child_process');const spawn=cp.spawn;
cp.spawn=function(file,args,options){if(file==='powershell.exe'&&args.some(a=>a.startsWith('& codex ')||a.startsWith('# ADE_COORDINATOR_LAUNCH'))){
 return spawn.call(this,${JSON.stringify(process.execPath)},[${JSON.stringify(resolve('scripts/fixtures/codex-conversation.cjs'))}],{...options,env:{...options.env,ADE_COORDINATOR_CONFIG:${JSON.stringify(JSON.stringify(config))}}});}
 return spawn.call(this,file,args,options);};
const original=cp.execFile;
cp.execFile=function(file,args,options,callback){
 if(!/tailscale(?:\\.exe)?$/i.test(file))return original.call(this,file,args,options,callback);
 const config={TCP:{'443':{HTTPS:true}},Web:{'ade-mobile.fixture.ts.net:443':{Handlers:{'/':{Proxy:'http://127.0.0.1:${port}'}}}}};
 queueMicrotask(()=>callback(null,JSON.stringify(args[0]==='status'?{BackendState:'Running',Self:{DNSName:'ade-mobile.fixture.ts.net.',Online:true}}:config)));return {};};
cp.execFile[require('node:util').promisify.custom]=(file,args,options)=>new Promise((done,fail)=>cp.execFile(file,args,options,(error,stdout,stderr)=>error?fail(error):done({stdout,stderr})));
const ipc=require('electron').ipcMain;const handle=ipc.handle.bind(ipc);
ipc.handle=(channel,listener)=>handle(channel,async(event,input)=>{const result=await listener(event,input);
 if(channel==='conversation:command'&&globalThis.adeDelayConversation){globalThis.adeDelayConversation=false;globalThis.adeConversationAdmitted=true;
 await new Promise(done=>{globalThis.adeReleaseConversation=done;});}return result;});
require(${JSON.stringify(resolve('out/main/index.js'))});`);
  const launch = async () => {
    app = await electron.launch({ args: [launcher, '--use-fake-device-for-media-stream'], cwd: resolve('.'), env: { ...process.env, ADE_USER_DATA_DIR: join(root, 'profile'), ADE_HOST_API_ENABLED: '0', ADE_MOBILE_PORT: String(port), NODE_ENV: 'test' } });
    const page = await app.firstWindow(); page.setDefaultTimeout(20_000); await page.waitForFunction(() => !!window.ade); return page;
  };
  let page = await launch();
  const agent = await page.evaluate(async () => {
    await window.ade.invoke('harness:setServiceKey', { name: 'ELEVENLABS_API_KEY', value: 'conversation-speech-fixture', scope: 'all' });
    const category = await window.ade.invoke('category:create', { name: 'Conversation' });
    return window.ade.invoke('agent:create', { categoryId: category.id, name: 'Central Codex', runtime: 'codex', permissionMode: 'bypass', codexModel: 'gpt-5.6-sol', codexReasoningEffort: 'high' });
  });
  const open = async (target: Page) => { await target.locator('#desktop-supervision').click(); await target.getByRole('button', { name: 'Mit ADE sprechen', exact: true }).click(); return target.getByRole('dialog', { name: 'ADE-Gespräch', exact: true }); };
  if (process.argv.includes('--actions-only')) { await coordinatorActionsFlow(page, root, port, agent.id, evidence, check); return; }
  let dialog = await open(page);
  await dialog.getByText('Noch kein ADE-Gespräch.', { exact: false }).waitFor();
  check('global dialog opens with no project or terminal', (await page.evaluate(() => window.ade.invoke('pty:list'))).sessions.length === 0 && (await page.evaluate(() => window.ade.invoke('config:get'))).repositories.length === 0);
  check('dialog receives keyboard focus', await dialog.evaluate(node => node.contains(document.activeElement)));
  const incomplete = await page.evaluate(async categoryId => window.ade.invoke('agent:create', { categoryId, name: 'Unconfigured Codex', runtime: 'codex', permissionMode: 'default' }), agent.categoryId);
  await dialog.getByLabel('Gesprächsprofil', { exact: true }).selectOption(incomplete.id);
  await page.evaluate(id => window.ade.invoke('agent:delete', { id }), incomplete.id);
  await dialog.getByRole('button', { name: 'Neues ADE-Gespräch', exact: true }).click();
  await dialog.getByRole('alert').waitFor();
  await expect(dialog.getByRole('button', { name: 'Neues ADE-Gespräch', exact: true })).toBeEnabled();
  check('confirmed removed-profile refusal leaves no pending creation and allows correcting the selection', !(await dialog.getByRole('button', { name: 'Neues Gespräch erneut prüfen', exact: true }).count()) && !(await page.evaluate(() => window.ade.invoke('conversation:get'))).length);
  await dialog.getByLabel('Gesprächsprofil', { exact: true }).selectOption(agent.id);
  await app!.evaluate(() => { (globalThis as unknown as { adeDelayConversation: boolean }).adeDelayConversation = true; });
  await dialog.getByRole('button', { name: 'Neues ADE-Gespräch', exact: true }).click();
  await page.waitForFunction(async () => (await window.ade.invoke('conversation:get')).length === 1);
  await page.keyboard.press('Escape'); await expect(page.locator('#desktop-supervision')).toBeFocused();
  check('Escape closes the dialog while creation acknowledgement is delayed', true);
  await page.reload(); dialog = await open(page);
  await dialog.getByRole('button', { name: 'Neues Gespräch erneut prüfen', exact: true }).click();
  await app!.evaluate(() => { (globalThis as unknown as { adeReleaseConversation: () => void }).adeReleaseConversation(); });
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled();
  check('desktop reload recovers delayed creation without duplicating the conversation', (await page.evaluate(() => window.ade.invoke('conversation:get'))).length === 1);
  const id = await dialog.getByLabel('Gespräch auswählen', { exact: true }).inputValue();
  check('empty conversation has no native result and launches no PTY', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).model === null && (await page.evaluate(() => window.ade.invoke('pty:list'))).sessions.length === 0);
  const send = async (text: string) => { await dialog.getByLabel('Nachricht an ADE', { exact: true }).fill(text); await dialog.getByRole('button', { name: 'An ADE senden', exact: true }).click(); };
  await send('remember:MORNING_CONTEXT'); await dialog.getByText('Recorded', { exact: true }).waitFor();
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled();
  await send('recall'); await dialog.getByText('MORNING_CONTEXT', { exact: true }).waitFor();
  check('second message retains exact conversation context', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.length === 2);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled(); await send('projects');
  await dialog.getByText('"total":0', { exact: false }).waitFor();
  check('ADE read tool returns the actual empty supervision inventory', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.at(-1)!.output.includes('"projects":[]'));
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled(); await send('question');
  await dialog.getByText('Womit beginnen?', { exact: true }).waitFor();
  await dialog.getByLabel('Deine Antwort', { exact: true }).fill('Mit dem Überblick');
  await dialog.getByRole('button', { name: 'Antwort senden', exact: true }).click();
  await dialog.getByText('Antwort empfangen', { exact: true }).waitFor();
  check('exact native question receives and acknowledges the answer', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.at(-1)!.questions[0]!.status === 'answered');
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled();
  await dialog.getByLabel('Nachricht an ADE', { exact: true }).fill('Unsent morning draft');
  await page.keyboard.press('Escape'); await expect(page.locator('#desktop-supervision')).toBeFocused();
  dialog = await open(page); await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(id);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toHaveValue('Unsent morning draft');
  check('closing and reopening restores the selected conversation draft', true);
  await dialog.getByLabel('Gesprächsprofil', { exact: true }).selectOption(agent.id);
  await dialog.getByRole('button', { name: 'Neues ADE-Gespräch', exact: true }).click();
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toHaveValue('');
  const secondId = await dialog.getByLabel('Gespräch auswählen', { exact: true }).inputValue();
  await dialog.getByLabel('Nachricht an ADE', { exact: true }).fill('Second context draft');
  await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(id);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toHaveValue('Unsent morning draft');
  check('switching conversations keeps unsent text on its exact target', secondId !== id);
  await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(secondId);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toHaveValue('Second context draft');
  await conversationVoiceFlow(page, id, check, 'desktop voice');
  check('desktop speech uses the provider exactly twice without creating any PTY', (await app!.evaluate(() => (globalThis as unknown as { adeSpeechStarts: number }).adeSpeechStarts)) === 2 && !(await page.evaluate(() => window.ade.invoke('pty:list'))).sessions.length);
  await send('remember:SECOND_CONTEXT'); await dialog.getByText('Recorded', { exact: true }).waitFor();
  check('second conversation gets its own native context', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), secondId)).turns.length === 1);
  await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(id);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toHaveValue('Unsent morning draft');
  check('work in another conversation leaves the original transcript unchanged', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.length === 4);
  await send('hold'); await dialog.getByText('ADE arbeitet', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  check('closing the dialog leaves the native conversation running', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.at(-1)!.status === 'working');
  dialog = await open(page); await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(id);
  await dialog.getByRole('button', { name: 'Antwort unterbrechen', exact: true }).click(); await dialog.getByText('Unterbrochen', { exact: true }).waitFor();
  check('explicit interruption reaches native turn confirmation', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.at(-1)!.status === 'interrupted');
  await app!.close(); app = undefined; page = await launch(); dialog = await open(page);
  await dialog.getByLabel('Gespräch auswählen', { exact: true }).selectOption(id);
  await expect(dialog.getByLabel('Nachricht an ADE', { exact: true })).toBeEnabled(); await send('recall');
  await expect(dialog.getByText('MORNING_CONTEXT', { exact: true })).toHaveCount(2);
  check('app restart resumes only the exact stored native conversation', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).turns.at(-1)!.output === 'MORNING_CONTEXT');
  for (const width of [800, 390]) {
    await app!.evaluate(({ BrowserWindow }, width) => { const w = BrowserWindow.getAllWindows()[0]!; w.setMinimumSize(320, 400); w.setSize(width, 850); }, width);
    check(`conversation fits ${width}px without horizontal overflow`, await dialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1 && node.getBoundingClientRect().right <= innerWidth));
    await dialog.evaluate(node => { node.scrollTop = 0; });
    await dialog.screenshot({ path: join(evidence, `conversation-${width}.png`) });
  }
  await dialog.getByRole('button', { name: 'Gespräch beenden', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'An ADE senden', exact: true })).toBeDisabled();
  check('ending the conversation keeps its transcript and disables sending', (await page.evaluate(id => window.ade.invoke('conversation:detail', { conversationId: id }), id)).closed);
  await dialog.getByRole('button', { name: 'Zur Projektbetreuung', exact: true }).click();
  await expect(page.locator('#ade-conversation-open')).toBeFocused();
  check('back navigation restores the explicit conversation opener', true);
  await conversationMobileFlow(page, port, agent.id, evidence, check);
  await coordinatorActionsFlow(page, root, port, agent.id, evidence, check);
}
void main().catch(async error => { failed++; console.error(error); if (app) { const page = await app.firstWindow(); console.error(await page.evaluate(() => ({ focus: document.activeElement?.tagName + '#' + document.activeElement?.id, text: document.querySelector('.conversation-panel')?.textContent }))); await page.screenshot({ path: join(evidence, 'conversation-failure.png') }); } }).finally(async () => {
  await app?.close();
  if (dirname(root) !== realpathSync.native(tmpdir())) throw new Error('Unexpected fixture root');
  rmSync(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 });
  console.log(`Conversation Electron: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
});
