import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { chromium, type Browser } from 'playwright';
import { createRemoteWorkspaceFixture } from './helpers/remoteWorkspaceFixture';
import { mobileTlsProxy } from './helpers/mobileBrowser';
import { BrowserSessions } from '../src/main/remote/BrowserSessions';
import { HostApiServer } from '../src/main/remote/HostApiServer';
import { RemoteAuthorizer } from '../src/main/remote/authorization';
import { loadMobileAssets } from '../src/main/remote/mobileAssets';
import type { RemoteCommandContext } from '../src/main/application/AdeApplicationService';
import { PNG } from 'pngjs';
import { commitDetailsFlow } from './helpers/commitDetailsFlow';

let passed = 0; let failed = 0;
const check = (name: string, ok: boolean): void => { if (ok) { passed++; console.log(`  ok  ${name}`); } else { failed++; console.error(`FAIL  ${name}`); } };
const root = mkdtempSync(join(tmpdir(), 'ade-workbench-browser-'));
let browser: Browser | undefined; let server: HostApiServer | undefined;
let proxy: Awaited<ReturnType<typeof mobileTlsProxy>> | undefined; let sessions: BrowserSessions | undefined;
void (async () => {
  const fixture = createRemoteWorkspaceFixture(root); const { application: app, store, devices } = fixture;
  devices.enroll('setup', 'Fixture setup', 'd'.repeat(40)); devices.setAdminScopes('setup', ['catalog:write']);
  const context = (): RemoteCommandContext => ({ principal: { id: 'setup', kind: 'device', proof: 'device-signature',
    scopes: new Set(devices.activeDevices().find((device) => device.id === 'setup')!.scopes) }, idempotencyKey: randomUUID(), requestId: 'browser-setup' });
  const first = (await app.administer(context(), { operation: 'project-create', input: { name: 'First project' } })).created!.id;
  const second = (await app.administer(context(), { operation: 'project-create', input: { name: 'Second project' } })).created!.id;
  const home = join(root, 'builder-home'); mkdirSync(home); writeFileSync(join(home, 'home.txt'), 'Home without project\r\n');
  store.save({ agents: store.get().agents.map((agent) => agent.id === 'builder' ? { ...agent, homeWorkspaceDir: home } : agent) });
  for (const repositoryId of [first, second]) await app.administer(context(), { operation: 'workspace-prepare', input: { agentId: 'builder', repositoryId } });
  const binding = store.get().workspaceBindings.find((item) => item.repositoryId === first)!;
  const other = store.get().workspaceBindings.find((item) => item.repositoryId === second)!;
  const historyGit = (...args: string[]) => execFileSync('git', ['-C', binding.workspaceDir, '-c', 'user.name=Tablet Author', '-c', 'user.email=tablet@example.test', '-c', 'commit.gpgSign=false', ...args], { windowsHide: true, encoding: 'utf8' });
  writeFileSync(join(binding.workspaceDir, 'history.txt'), 'before\nkeep\n'); historyGit('add', '--', 'history.txt'); historyGit('commit', '-m', 'Initial history');
  writeFileSync(join(binding.workspaceDir, 'history.txt'), 'after\nkeep\nextra\n'); writeFileSync(join(binding.workspaceDir, 'badge.bin'), Buffer.from([0, 1, 2]));
  historyGit('add', '--', 'history.txt', 'badge.bin'); historyGit('commit', '-m', 'Review tablet history\n\nWhy this layout changed.');
  const historySha = historyGit('rev-parse', 'HEAD').trim();
  mkdirSync(join(binding.workspaceDir, 'docs')); writeFileSync(join(binding.workspaceDir, 'docs', 'guide.md'), '# First workspace\n');
  execFileSync('git', ['-C', binding.workspaceDir, 'add', '--', 'docs/guide.md'], { windowsHide: true });
  writeFileSync(join(binding.workspaceDir, 'docs', 'guide.md'), '# First workspace\nSmall change\n');
  writeFileSync(join(binding.workspaceDir, '.env'), 'SECRET=fixture-hidden');
  writeFileSync(join(other.workspaceDir, 'second.txt'), 'Second workspace only\n');
  proxy = await mobileTlsProxy(); sessions = new BrowserSessions(devices);
  server = new HostApiServer(app, { port: 0, heartbeatMs: 200, requireDeviceReads: true,
    authorizer: new RemoteAuthorizer('t'.repeat(32), [], undefined, devices),
    browser: { origin: proxy.origin, sessions, assets: loadMobileAssets(resolve(process.env.ADE_MOBILE_ASSETS ?? 'out/mobile')) }, audit: (entry) => devices.audit(entry) });
  proxy.target((await server.start()).port);
  browser = await chromium.launch({ args: ['--ignore-certificate-errors', '--host-resolver-rules=MAP ade-mobile.fixture.ts.net 127.0.0.1'] });
  const page = await browser.newPage({ viewport: { width: 1024, height: 768 }, hasTouch: true, ignoreHTTPSErrors: true }); page.setDefaultTimeout(25_000);
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(sessions.beginPairing(proxy.origin).url); await page.getByRole('button', { name: 'Dieses Gerät verbinden', exact: true }).click();
  await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await page.getByRole('button', { name: 'Workspace für Builder', exact: true }).click();
  const workspace = page.getByRole('dialog', { name: 'Workspace · Builder', exact: true });
  await workspace.getByRole('alert').waitFor();
  check('agent opens an accessible workspace with explicit missing permission', await workspace.evaluate((node) => node.contains(document.activeElement))
    && (await workspace.getByRole('alert').innerText()).includes('freigeben'));
  const deviceId = devices.activeDevices().find((device) => device.id !== 'setup')!.id;
  devices.setAdminScopes(deviceId, ['workspace:read', 'workspace:write']);
  await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await workspace.getByRole('button', { name: 'Workspace aktualisieren', exact: true }).click();
  await workspace.getByRole('button', { name: 'home.txt', exact: true }).waitFor();
  check('agent without default opens home even when projects exist', await workspace.getByLabel('Workspace-Projekt', { exact: true }).inputValue() === ''
    && await workspace.getByRole('button', { name: 'Git-Änderungen', exact: true }).isDisabled());
  await workspace.getByRole('button', { name: 'home.txt', exact: true }).click();
  await workspace.getByRole('button', { name: 'Datei bearbeiten', exact: true }).click();
  await workspace.getByRole('textbox', { name: 'Datei bearbeiten', exact: true }).fill('Home edited\n');
  await workspace.getByRole('button', { name: 'Datei speichern', exact: true }).click();
  await workspace.getByRole('button', { name: 'home.txt', exact: true }).waitFor();
  check('tablet edits a projectless home file', readFileSync(join(home, 'home.txt'), 'utf8') === 'Home edited\r\n');
  await workspace.getByLabel('Workspace-Projekt', { exact: true }).selectOption(first);
  await workspace.getByRole('button', { name: 'docs', exact: true }).waitFor();
  check('files load without starting any runtime', fixture.sessions.length === 0 && !await workspace.getByRole('button', { name: '.env', exact: true }).count());
  await workspace.getByRole('button', { name: 'docs', exact: true }).click();
  await workspace.getByRole('button', { name: 'guide.md', exact: true }).click();
  await workspace.getByLabel('Dateivorschau', { exact: true }).waitFor();
  check('nested file content and focus match selected workspace', (await workspace.getByLabel('Dateivorschau', { exact: true }).innerText()).includes('Small change')
    && await workspace.locator('h3').filter({ hasText: 'docs/guide.md' }).evaluate((node) => node === document.activeElement));
  await workspace.getByRole('button', { name: 'Zurück zur Liste', exact: true }).click();
  await page.waitForFunction(() => document.activeElement?.textContent?.includes('guide.md'));
  check('closing file restores the file opener', true);
  await workspace.getByLabel('Dateinamen suchen', { exact: true }).fill('guide'); await workspace.getByRole('button', { name: 'Dateien suchen', exact: true }).click();
  await workspace.getByRole('button', { name: 'docs/guide.md', exact: true }).waitFor(); check('filename search reaches nested files', true);
  await workspace.getByRole('button', { name: 'Git-Änderungen', exact: true }).click();
  await workspace.getByRole('button', { name: 'Arbeitsdatei vergleichen', exact: true }).click();
  await workspace.getByLabel('Git-Diff', { exact: true }).waitFor();
  check('Git diff shows actual uncommitted lines', (await workspace.getByLabel('Git-Diff', { exact: true }).innerText()).includes('+Small change'));
  await workspace.getByRole('button', { name: 'Zurück zur Liste', exact: true }).click();
  await workspace.getByRole('button', { name: 'Vorgemerkte Änderung', exact: true }).click();
  await workspace.getByLabel('Git-Diff', { exact: true }).waitFor();
  check('index diff is separate from working file', !(await workspace.getByLabel('Git-Diff', { exact: true }).innerText()).includes('Small change'));
  await commitDetailsFlow(page, workspace, historySha, check);
  await workspace.getByLabel('Workspace-Projekt', { exact: true }).selectOption(second);
  await workspace.getByRole('button', { name: 'Dateien', exact: true }).click();
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).waitFor();
  check('project switch clears old contents and selects the correct binding', !await workspace.getByLabel('Git-Diff', { exact: true }).count()
    && !await workspace.getByRole('button', { name: 'guide.md', exact: true }).count());
  await page.setViewportSize({ width: 390, height: 844 });
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).click();
  await workspace.getByLabel('Dateivorschau', { exact: true }).waitFor();
  check('phone detail uses available width without horizontal overflow', await workspace.evaluate((node) => node.scrollWidth <= node.clientWidth + 1));
  check('phone replaces file list with its detail', !await workspace.getByRole('region', { name: 'Workspace-Dateien', exact: true }).isVisible());
  await workspace.getByRole('button', { name: 'Datei bearbeiten', exact: true }).click();
  const editor = workspace.getByRole('textbox', { name: 'Datei bearbeiten', exact: true });
  await editor.fill('Draft from tablet\n');
  await workspace.getByRole('button', { name: 'Rückgängig', exact: true }).click();
  check('editor undo restores previous content', (await editor.inputValue()).includes('Second workspace only'));
  await editor.fill('Draft from tablet\n');
  await workspace.getByLabel('Im Text suchen', { exact: true }).fill('tablet'); await workspace.getByRole('button', { name: 'Weitersuchen', exact: true }).click();
  check('editor search selects matching text', await editor.evaluate((node) => { const input = node as HTMLTextAreaElement; return input.value.slice(input.selectionStart, input.selectionEnd) === 'tablet'; }));
  await page.keyboard.press('Escape'); await workspace.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Workspace für Builder', exact: true }).click();
  await workspace.getByLabel('Workspace-Projekt', { exact: true }).selectOption(second);
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).click();
  check('unsaved file draft survives closing and reopening its project', await editor.inputValue() === 'Draft from tablet\n');
  writeFileSync(join(other.workspaceDir, 'second.txt'), 'External edit from PC\n');
  await workspace.getByRole('button', { name: 'Datei speichern', exact: true }).click();
  await workspace.getByRole('region', { name: 'Dateikonflikt', exact: true }).waitFor();
  check('conflict comparison preserves both host change and tablet draft', (await workspace.getByRole('region', { name: 'Dateikonflikt', exact: true }).innerText()).includes('External edit from PC')
    && await editor.inputValue() === 'Draft from tablet\n' && readFileSync(join(other.workspaceDir, 'second.txt'), 'utf8') === 'External edit from PC\n');
  mkdirSync(resolve('test-results/remote'), { recursive: true });
  await page.screenshot({ path: resolve('test-results/remote/workbench-editor-conflict.png') });
  await editor.fill('External edit from PC\nMerged tablet edit\n');
  await workspace.getByRole('button', { name: 'Aktuellen Stand als Basis bestätigen', exact: true }).click();
  proxy.loseWorkspaceReplies(true);
  await workspace.getByRole('button', { name: 'Datei speichern', exact: true }).click();
  await workspace.getByRole('button', { name: 'Speicherstatus erneut prüfen', exact: true }).waitFor();
  await workspace.getByRole('alert').waitFor(); proxy.loseWorkspaceReplies(false);
  check('lost save reply leaves exact pending draft available', await editor.isDisabled() && readFileSync(join(other.workspaceDir, 'second.txt'), 'utf8').includes('Merged tablet edit'));
  await page.keyboard.press('Escape'); await workspace.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Workspace für Builder', exact: true }).click();
  await workspace.getByLabel('Workspace-Projekt', { exact: true }).selectOption(second);
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).click();
  await workspace.getByRole('button', { name: 'Speicherstatus erneut prüfen', exact: true }).click();
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).waitFor();
  check('same save receipt recovers across dialog closure', !await workspace.getByRole('button', { name: 'Speicherstatus erneut prüfen', exact: true }).count());
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).click();
  await workspace.getByLabel('Dateivorschau', { exact: true }).waitFor();
  check('saved content is visible after explicit confirmation', (await workspace.getByLabel('Dateivorschau', { exact: true }).innerText()).includes('Merged tablet edit'));
  await workspace.getByRole('button', { name: 'Agent-Profil', exact: true }).click();
  await workspace.getByLabel('Profil-Agentname', { exact: true }).waitFor();
  check('profile editor explains its separate permission', await workspace.getByRole('button', { name: 'Profil speichern', exact: true }).isDisabled());
  devices.setAdminScopes(deviceId, ['workspace:read', 'workspace:write', 'profiles:write']);
  await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  await workspace.getByRole('button', { name: 'Profil neu laden', exact: true }).click();
  const png = new PNG({ width: 24, height: 24 }); png.data.fill(190);
  await workspace.getByLabel('Profilbild auswählen', { exact: true }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: PNG.sync.write(png) });
  await workspace.getByRole('img', { name: 'Profilbild-Vorschau', exact: true }).waitFor();
  await workspace.getByLabel('Profil-Rolle', { exact: true }).fill('Tablet reviewer');
  await workspace.getByRole('button', { name: 'Profil speichern', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.m-agent-profile button')?.hasAttribute('disabled'));
  check('browser normalizes and stores a tablet profile image', !!store.get().agents.find((agent) => agent.id === 'builder')!.photo
    && store.get().agents.find((agent) => agent.id === 'builder')!.role === 'Tablet reviewer');
  check('authenticated image is displayed under mobile CSP', await workspace.getByRole('img', { name: 'Profilbild-Vorschau', exact: true }).evaluate((node) => (node as HTMLImageElement).naturalWidth > 0));
  // Model and reasoning are editable from the tablet for a native Codex profile; the catalog comes from the PC.
  const builderBefore = store.get().agents.find((agent) => agent.id === 'builder')!;
  store.save({ agents: store.get().agents.map((agent) => agent.id === 'builder' ? { ...agent, runtime: 'codex', customCommand: undefined, codexModel: 'gpt-5.6-sol', codexReasoningEffort: 'high' } : agent) });
  await workspace.getByRole('button', { name: 'Profil neu laden', exact: true }).click();
  const modelSelect = workspace.getByLabel('Codex-Modell', { exact: true }); await modelSelect.waitFor();
  await workspace.getByRole('option', { name: /Codex fixture fast/ }).waitFor({ state: 'attached' });
  check('the PC model catalog fills the tablet model choice with the default marked', (await modelSelect.locator('option').allTextContents()).join('|') === 'GPT-5.6 Sol · gpt-5.6-sol · Standard|Codex fixture fast · codex-fixture-fast');
  await modelSelect.selectOption('codex-fixture-fast');
  check('choosing a model narrows the reasoning choices to what the model reports', await workspace.getByLabel('Denktiefe', { exact: true }).inputValue() === 'low' && await workspace.getByLabel('Denktiefe', { exact: true }).locator('option').count() === 1);
  await workspace.getByLabel('Berechtigungsmodus', { exact: true }).selectOption('bypass');
  check('the permission mode shows the exact start command it produces', (await workspace.locator('.m-profile-model code').last().textContent()) === 'codex --dangerously-bypass-approvals-and-sandbox');
  await workspace.getByRole('button', { name: 'Profil speichern', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.m-agent-profile button')?.hasAttribute('disabled'));
  check('tablet saves the permission mode into the profile', store.get().agents.find((agent) => agent.id === 'builder')!.permissionMode === 'bypass');
  check('tablet saves model and reasoning into the Codex profile', store.get().agents.find((agent) => agent.id === 'builder')!.codexModel === 'codex-fixture-fast' && store.get().agents.find((agent) => agent.id === 'builder')!.codexReasoningEffort === 'low');
  store.save({ agents: store.get().agents.map((agent) => agent.id === 'builder' ? { ...agent, runtime: builderBefore.runtime, customCommand: builderBefore.customCommand, permissionMode: builderBefore.permissionMode, codexModel: undefined, codexReasoningEffort: undefined } : agent) });
  await workspace.getByRole('button', { name: 'Profil neu laden', exact: true }).click();
  await workspace.getByLabel('Profil-Rolle', { exact: true }).waitFor();
  check('custom-command profiles show no model or permission controls', await workspace.getByLabel('Codex-Modell', { exact: true }).count() === 0 && await workspace.getByLabel('Berechtigungsmodus', { exact: true }).count() === 0);
  const photoOpener = workspace.getByRole('button', { name: 'Profilbild vergrössern', exact: true });
  await photoOpener.focus(); await photoOpener.press('Enter');
  const photoDialog = page.getByRole('dialog', { name: 'Profilbild · Builder', exact: true }); await photoDialog.waitFor();
  check('profile photo opens enlarged with focus inside the viewer', await photoDialog.evaluate(node => node.contains(document.activeElement))
    && (await photoDialog.getByRole('img').boundingBox())!.width > 96);
  check('enlarged profile photo fits a phone viewport', await photoDialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1));
  await page.keyboard.press('Escape'); await photoDialog.waitFor({ state: 'hidden' });
  check('closing photo retains the profile and restores photo button focus', await workspace.isVisible() && await photoOpener.evaluate(node => node === document.activeElement));
  await photoOpener.click(); await photoDialog.getByRole('button', { name: 'Zurück zum Profil', exact: true }).click();
  await photoDialog.waitFor({ state: 'hidden' });
  check('touch photo viewer returns without discarding profile edits', await workspace.getByLabel('Profil-Rolle', { exact: true }).inputValue() === 'Tablet reviewer');
  await workspace.getByRole('button', { name: 'Profilbild entfernen', exact: true }).click();
  await workspace.getByRole('button', { name: 'Profil speichern', exact: true }).click();
  await workspace.getByRole('img', { name: 'Profilbild-Vorschau', exact: true }).waitFor({ state: 'hidden' });
  check('profile removal restores the initials view', !store.get().agents.find((agent) => agent.id === 'builder')!.photo);
  await workspace.getByRole('button', { name: 'Dateien', exact: true }).click();
  await workspace.getByRole('button', { name: 'second.txt', exact: true }).click();
  await workspace.getByLabel('Dateivorschau', { exact: true }).waitFor();
  await workspace.getByRole('button', { name: 'Zurück zur Liste', exact: true }).click();
  await page.keyboard.press('Escape'); await workspace.waitFor({ state: 'hidden' });
  check('workspace dialog returns focus to the selected agent', await page.getByRole('button', { name: 'Workspace für Builder', exact: true }).evaluate((node) => node === document.activeElement));
  // The overview offers a direct way to the profile so nobody has to find the tab row behind a focused terminal.
  const profileOpener = page.getByRole('button', { name: 'Profil bearbeiten: Builder', exact: true });
  await profileOpener.click(); await workspace.waitFor();
  await workspace.getByLabel('Profil-Agentname', { exact: true }).waitFor();
  check('overview opens the workspace directly on the profile tab', await workspace.getByRole('button', { name: 'Agent-Profil', exact: true }).getAttribute('aria-pressed') === 'true' && await workspace.getByLabel('Workspace-Projekt', { exact: true }).isVisible());
  await page.keyboard.press('Escape'); await workspace.waitFor({ state: 'hidden' });
  check('closing the profile workspace returns focus to its overview button', await profileOpener.evaluate((node) => node === document.activeElement));
  await page.reload(); await page.getByRole('status').filter({ hasText: /^Verbunden$/ }).waitFor();
  check('a reloaded tablet does not reopen the profile on its own', await workspace.count() === 0 || !await workspace.isVisible());
  check('workspace flow has no uncaught browser errors', errors.length === 0);
  mkdirSync(resolve('test-results/remote'), { recursive: true }); await page.screenshot({ path: resolve('test-results/remote/workbench-phone.png') });
})().catch((error) => { failed++; console.error(error); }).finally(async () => {
  await browser?.close(); await server?.stop(); sessions?.dispose(); await proxy?.close();
  rmSync(root, { recursive: true, force: true }); console.log(`Remote workbench browser: ${passed} passed, ${failed} failed`); process.exitCode = failed ? 1 : 0;
});
