import { linkSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { DEFAULT_CONFIG, type SessionMeta, type Run } from '../src/shared/types';
import { validSupervisionCommand, type SupervisionCommand, type SupervisionAction } from '../src/shared/supervision';
import { SupervisionStore } from '../src/main/supervision/SupervisionStore';
import { SupervisionService } from '../src/main/supervision/SupervisionService';
import { assertIpcPayload } from '../src/main/ipcValidation';
import { CHANNEL_POLICY, REMOTE_COMMAND_CHANNELS } from '../src/main/ipcPolicy';

const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-supervision-'))); const path = join(root, 'supervision.json');
let passed = 0; let failed = 0; let sequence = 0;
const check = (label: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${label}`); } else { failed++; console.error(`FAIL  ${label}`); } };
const throws = (fn: () => unknown) => { try { fn(); return false; } catch { return true; } };
try {
  const config = structuredClone(DEFAULT_CONFIG);
  config.repositories = ['a', 'b', 'c'].map(id => ({ id, name: 'Same name', rootPath: join(root, id), commonGitDir: join(root, id, '.git'), executionBackend: 'native', verified: true, createdAt: 1 }));
  const sessions: SessionMeta[] = ['a', 'b', 'c'].map(id => ({ id: `session-${id}`, repositoryId: id, projectWorkspaceId: `workspace-${id}`, title: 'CLI', kind: 'interactive', runtime: 'codex', status: 'running', createdAt: 1 }));
  config.runs = [{ id: 'run-a', name: 'Run', repositoryId: 'a', status: 'running' } as Run];
  const create = () => new SupervisionService(new SupervisionStore(path), { get: () => config }, id => sessions.find(s => s.id === id));
  let service = create();
  const command = (input: SupervisionAction) => service.command({ ...input, revision: service.query().revision, commandId: `command-${++sequence}` } as SupervisionCommand);
  check('new supervision is empty and does not infer a model profile', !service.query().projects.length && !service.query().profile);
  for (const id of ['a', 'b', 'c']) command({ operation: 'project', repositoryId: id, mode: id === 'b' ? 'observe' : 'coordinate', objective: `Private instruction ${id}` });
  let view = service.query();
  check('same project names retain three independent durable identities', view.projects.length === 3 && new Set(view.projects.map(p => p.id)).size === 3);
  check('summary carries digests and lengths without instruction bodies or host paths', !JSON.stringify(view).includes('Private instruction') && !JSON.stringify(view).includes(root) && view.projects[0]!.objective.chars > 0);
  check('explicit detail query returns the complete instruction', service.detail(view.projects[0]!.id).objective === 'Private instruction a');
  const a = view.projects[0]!.id; const b = view.projects[1]!.id;
  command({ operation: 'link', projectId: a, target: { kind: 'session', id: 'session-a' } });
  command({ operation: 'link', projectId: a, target: { kind: 'run', id: 'run-a' } });
  check('session and independent run keep different relation types', service.query().projects[0]!.links.map(l => l.target.kind).join() === 'session,run');
  check('wrong-project session is rejected even with the same display name', throws(() => command({ operation: 'link', projectId: b, target: { kind: 'session', id: 'session-a' } })));
  check('wrong-project run is rejected', throws(() => command({ operation: 'link', projectId: b, target: { kind: 'run', id: 'run-a' } })));
  const before = readFileSync(path, 'utf8');
  check('duplicate links are rejected without writing state', throws(() => command({ operation: 'link', projectId: a, target: { kind: 'session', id: 'session-a' } })) && readFileSync(path, 'utf8') === before);
  const replay: SupervisionCommand = { operation: 'project', repositoryId: 'a', mode: 'direct', objective: 'Confirmed new scope', commandId: 'stable-key', revision: service.query().revision };
  service.command(replay); service = create();
  check('explicit direct mode and assignments survive host restart', service.query().projects[0]!.mode === 'direct' && service.query().projects[0]!.links.length === 2);
  check('same command is replayed durably without a second revision', service.command(replay).replayed && service.query().revision === replay.revision + 1);
  check('changed command cannot reuse its idempotency key', throws(() => service.command({ ...replay, objective: 'Conflicting' })));
  check('old tablet or desktop revision cannot replace newer ownership', throws(() => service.command({ ...replay, commandId: 'stale-new-key', revision: 0 })));
  const leaseCount = config.runWorkspaceLeases.length;
  check('metadata changes leave processes, runs and workspace leases untouched', sessions.every(s => s.status === 'running') && config.runs[0]!.status === 'running' && config.runWorkspaceLeases.length === leaseCount);
  config.repositories[0]!.name = 'Renamed';
  check('rename changes only the current display name', service.query().projects[0]!.name === 'Renamed' && service.query().projects[0]!.id === a);
  sessions.splice(0, 1); config.repositories.splice(0, 1);
  view = service.query();
  check('removed project/session stays explicit and never rebinds by name', !view.projects[0]!.available && !view.projects[0]!.links[0]!.available && view.projects[0]!.id === a);
  command({ operation: 'unlink', projectId: a, linkId: view.projects[0]!.links[0]!.id });
  check('unlinking supervision retains the independently running work', config.runs[0]!.status === 'running' && service.query().projects[0]!.links.length === 1);
  check('unknown payload fields and injected targets fail closed', !validSupervisionCommand({ ...replay, cwd: root }) && !validSupervisionCommand({ ...replay, commandId: '../path' }));
  check('IPC validates exact request shape', throws(() => assertIpcPayload('supervision:get', {})) && throws(() => assertIpcPayload('supervision:detail', { projectId: a, text: 'leak' })));
  check('new metadata channels do not expand remote command or shell authority', CHANNEL_POLICY['supervision:command'].surface === 'desktop' && !REMOTE_COMMAND_CHANNELS.includes('supervision:command'));
  const original = readFileSync(path, 'utf8'); writeFileSync(path, original + ' ');
  check('external store drift is refused without overwriting its bytes', throws(() => command({ operation: 'profile', agentId: null })) && readFileSync(path, 'utf8') === original + ' ');
  writeFileSync(path, original); service = create(); command({ operation: 'profile', agentId: null });
  check('final positive write succeeds after reloading verified state', service.query().revision > replay.revision);
  const malformed = join(root, 'malformed.json'); writeFileSync(malformed, '{"broken":true}');
  check('malformed existing store is retained, never silently reset', throws(() => new SupervisionStore(malformed)) && readFileSync(malformed, 'utf8') === '{"broken":true}');
  const corruptPath = join(root, 'invalid-encoding.json'); const corrupt = Buffer.from(original);
  const objectiveOffset = corrupt.indexOf('"objective":"') + '"objective":"'.length;
  if (objectiveOffset < '"objective":"'.length) throw new Error('Fixture has no objective');
  corrupt[objectiveOffset] = 0xff; writeFileSync(corruptPath, corrupt);
  check('invalid UTF-8 inside otherwise valid state is refused byte-for-byte', throws(() => new SupervisionStore(corruptPath)) && readFileSync(corruptPath).equals(corrupt));
  const oversized = join(root, 'oversized.json'); writeFileSync(oversized, Buffer.alloc(2 * 1024 * 1024 + 1, 32));
  let sizeRefused = false; try { new SupervisionStore(oversized); } catch (error) { sizeRefused = error instanceof Error && error.message.includes('zu grosser'); }
  check('oversized storage is rejected by the byte boundary before JSON parsing', sizeRefused);
  writeFileSync(corruptPath, original);
  check('final storage control accepts a separately restored valid UTF-8 file', new SupervisionStore(corruptPath).snapshot().projects.length === 3);
  const hardlink = join(root, 'linked.json'); linkSync(path, hardlink);
  check('hard-linked store is refused', throws(() => new SupervisionStore(hardlink)));
} catch (error) { failed++; console.error(error); }
finally { if (dirname(root) !== realpathSync.native(tmpdir())) throw new Error('Unexpected fixture root'); rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
console.log(`Supervision: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
