import { execFileSync } from 'node:child_process';
import { linkSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRemoteWorkspaceFixture } from './helpers/remoteWorkspaceFixture';
import { IntegrationService } from '../src/main/repositories/IntegrationService';
import { validIntegrationCommand, validIntegrationQuery } from '../src/shared/integrationRequests';
import type { IntegrationReport } from '../src/shared/remote';
import { RemoteApiError, type RemoteCommandContext } from '../src/main/application/AdeApplicationService';
import { assertIpcPayload } from '../src/main/ipcValidation';
import { CHANNEL_POLICY, REMOTE_COMMAND_CHANNELS } from '../src/main/ipcPolicy';

let passed = 0;
const check = (label: string, condition: boolean) => { if (!condition) throw new Error(label); passed++; console.log(`  ok  ${label}`); };
async function refuses(label: string, action: () => unknown, pattern: RegExp) {
  try { await action(); } catch (error) { check(label, pattern.test(`${error instanceof RemoteApiError ? error.code : ''} ${String(error)}`)); return; } throw new Error(label);
}
const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-integration-')));
const git = (cwd: string, ...args: string[]) => execFileSync('git', ['-C', cwd, '-c', 'core.hooksPath=NUL', '-c', 'user.name=Fixture', '-c', 'user.email=fixture@localhost', '-c', 'commit.gpgSign=false', ...args], { windowsHide: true, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
void (async () => {
  const fixture = createRemoteWorkspaceFixture(root); const { store, projects, sessions } = fixture;
  const target = join(root, 'project'); const source = join(root, 'old-work'); mkdirSync(target);
  git(target, 'init', '--initial-branch=main'); git(target, 'config', 'core.autocrlf', 'false');
  writeFileSync(join(target, 'package.json'), JSON.stringify({ scripts: { verify: 'node check.cjs' } }));
  writeFileSync(join(target, 'check.cjs'), 'const fs = require("node:fs"); if (!fs.readFileSync("part.txt", "utf8").includes("palette")) process.exit(3); console.log("project check passed");\n');
  writeFileSync(join(target, 'part.txt'), 'base\n'); writeFileSync(join(target, 'current.txt'), 'base\n');
  git(target, 'add', '.'); git(target, 'commit', '-m', 'base'); const base = git(target, 'rev-parse', 'HEAD');
  git(target, 'worktree', 'add', '-b', 'old', source, base);
  writeFileSync(join(source, 'part.txt'), 'palette\n'); writeFileSync(join(source, 'unselected.txt'), 'do not transfer\n');
  git(source, 'add', '.'); git(source, 'commit', '-m', 'old palette');
  writeFileSync(join(source, 'local.txt'), 'local source edit\n'); writeFileSync(join(source, 'AGENTS.md'), 'Agent instructions remain here\n');
  writeFileSync(join(target, 'current.txt'), 'newer main feature\n'); git(target, 'add', '.'); git(target, 'commit', '-m', 'newer feature');
  const repository = { id: 'repo', name: 'Integration fixture', rootPath: target, commonGitDir: realpathSync.native(join(target, '.git')), executionBackend: 'native' as const, verified: true, createdAt: Date.now() };
  store.save({ repositories: [repository], workspaceBindings: [], projectWorkspaces: [] });
  const data = join(root, 'review-data'); const service = new IntegrationService(store, projects, () => sessions, data);
  const list = (await service.query({ operation: 'sources', repositoryId: 'repo' }, 'desktop')).sources!;
  check('discovers existing old worktree without registering or changing it', list.length === 1 && list[0]!.branch === 'old' && !store.get().projectWorkspaces.length);
  const preview = () => service.query({ operation: 'preview', repositoryId: 'repo', sourceId: list[0]!.id }, 'desktop');
  const first = (await preview()).preview!;
  check('read-only comparison shows divergent commits and local files', first.ownCommits === 1 && first.behind === 1 && first.files.some((file) => file.path === 'local.txt' && file.local));
  check('agent instructions default to unselected', first.files.some((file) => file.path === 'AGENTS.md' && !file.suggested && file.selectable));
  const diff = (await service.query({ operation: 'diff', previewId: first.id, path: 'part.txt' }, 'desktop')).diff!;
  check('three-way comparison exposes actual bounded base source and target contents', diff.base === 'base\n' && diff.source === 'palette\n' && diff.target === 'base\n' && !diff.limited);
  await refuses('comparison cannot escape the preview file selection', () => service.query({ operation: 'diff', previewId: first.id, path: 'package.json' }, 'desktop'), /nicht in dieser Vorschau/);
  await refuses('another device cannot read a private preview comparison', () => service.query({ operation: 'diff', previewId: first.id, path: 'part.txt' }, 'other'), /andere Sitzung/);
  check('wire preview carries no host paths', !JSON.stringify(first).includes(root.replace(/\\/g, '\\\\')));
  check('strict query and command payload reject injected paths or argv', !validIntegrationQuery({ operation: 'sources', repositoryId: 'repo', path: root })
    && !validIntegrationCommand({ operation: 'prepare', previewId: first.id, paths: ['../escape'] }) && !validIntegrationCommand({ operation: 'test', integrationId: 'id', command: 'anything' }));
  await refuses('preview is owned by its requester', () => service.command({ operation: 'prepare', previewId: first.id, paths: ['part.txt'] }, 'other'), /andere Sitzung/);
  writeFileSync(join(source, 'local.txt'), 'changed after preview\n');
  await refuses('source change invalidates preview before writes', () => service.command({ operation: 'prepare', previewId: first.id, paths: ['part.txt'] }, 'desktop'), /seit der Vorschau geändert/);
  const renewed = (await preview()).preview!;
  const outsideRefs = join(root, 'redirected-refs'); mkdirSync(outsideRefs); const refLink = join(repository.commonGitDir, 'refs', 'ade');
  symlinkSync(outsideRefs, refLink, process.platform === 'win32' ? 'junction' : 'dir');
  await refuses('redirected private Git ref namespace blocks preparation', () => service.command({ operation: 'prepare', previewId: renewed.id, paths: ['part.txt'] }, 'desktop'), /Verknüpfung/);
  if (!refLink.startsWith(root + (process.platform === 'win32' ? '\\' : '/')) || !realpathSync(refLink).startsWith(root)) throw new Error('Unexpected fixture link target.');
  rmSync(refLink, { recursive: true });
  sessions.push({ id: 'busy', agentId: 'builder', title: 'shell', kind: 'interactive', status: 'running', createdAt: Date.now(), workspaceDir: source, executionBackend: 'native' });
  await refuses('running source terminal blocks preparation', () => service.command({ operation: 'prepare', previewId: renewed.id, paths: ['part.txt'] }, 'desktop'), /Terminal/); sessions.length = 0;
  store.save({ runWorkspaceLeases: [{ id: 'integration-lease', runId: 'run', participantId: 'participant', agentId: 'builder', workspaceDir: join(root, 'other-leased-copy'),
    isRepo: true, branch: 'leased', baseSha: base, commonGitDir: repository.commonGitDir, status: 'active', acquiredAt: 1 }] });
  await refuses('lease in another checkout protects the shared repository', () => service.command({ operation: 'prepare', previewId: renewed.id, paths: ['part.txt'] }, 'desktop'), /verwalteter Auftrag/);
  store.save({ runWorkspaceLeases: [] });
  const sourceBefore = [git(source, 'rev-parse', 'HEAD'), git(source, 'status', '--porcelain=v1'), readFileSync(join(source, '.git'), 'utf8'), readFileSync(join(source, 'local.txt'), 'utf8')];
  const prepared = (await service.command({ operation: 'prepare', previewId: renewed.id, paths: ['part.txt', 'local.txt'] }, 'desktop')).report!;
  check('preparation creates registered separate review workspace', prepared.phase === 'review' && !!prepared.workspaceId && prepared.branch.startsWith('ade/integration-'));
  const review = store.get().projectWorkspaces.find((item) => item.id === prepared.workspaceId)!.workspaceDir;
  check('source HEAD index status and local bytes remain unchanged', JSON.stringify(sourceBefore) === JSON.stringify([git(source, 'rev-parse', 'HEAD'), git(source, 'status', '--porcelain=v1'), readFileSync(join(source, '.git'), 'utf8'), readFileSync(join(source, 'local.txt'), 'utf8')]));
  check('selected committed and dirty content combines with newer main', readFileSync(join(review, 'part.txt'), 'utf8') === 'palette\n' && readFileSync(join(review, 'current.txt'), 'utf8') === 'newer main feature\n' && readFileSync(join(review, 'local.txt'), 'utf8').includes('changed after'));
  check('unselected source commit files are absent from snapshot ancestry', !git(review, 'ls-tree', '-r', '--name-only', `refs/ade/integrations/${prepared.id}/source`).includes('unselected.txt'));
  await refuses('integration requires successful tests', () => service.command({ operation: 'integrate', integrationId: prepared.id, revision: prepared.revision, message: 'palette' }, 'desktop'), /Keine gültige Freigabe/);
  const reload = new IntegrationService(store, projects, () => sessions, data);
  check('prepared report and workspace survive service restart', (await reload.query({ operation: 'report', integrationId: prepared.id }, 'desktop')).report?.workspaceId === prepared.workspaceId);
  const test = async (runner = reload): Promise<IntegrationReport> => {
    const started = await runner.command({ operation: 'test', integrationId: prepared.id }, 'desktop'); check('test start returns durable running state', started.report?.phase === 'testing');
    const until = Date.now() + 60_000; while (runner.busy() && Date.now() < until) await new Promise((resolve) => setTimeout(resolve, 100));
    check('owned project test process finishes', !runner.busy());
    return (await runner.query({ operation: 'report', integrationId: prepared.id }, 'desktop')).report!;
  };
  writeFileSync(join(review, 'part.txt'), 'broken\n');
  const failed = await test(); check('real failing project check denies proof', !failed.tested && failed.checks[0]?.status === 'failed' && failed.checks[0]?.exitCode !== 0);
  writeFileSync(join(review, 'part.txt'), 'palette\n'); const ready = await test();
  check('positive control records real pnpm output and proof', ready.tested && ready.checks.every((item) => item.status === 'passed') && ready.checks[0]!.output.includes('project check passed'));
  writeFileSync(join(review, 'local.txt'), 'changed after tests\n');
  await refuses('post-test file edit invalidates approval', () => reload.command({ operation: 'integrate', integrationId: prepared.id, revision: ready.revision, message: 'palette' }, 'desktop'), /Keine gültige Freigabe/);
  const retested = await test();
  const integrated = (await reload.command({ operation: 'integrate', integrationId: prepared.id, revision: retested.revision, message: 'feat: reviewed palette' }, 'desktop')).report!;
  check('explicit approval commits reviewed work and fast-forwards main', integrated.phase === 'integrated' && integrated.integratedCommit === git(target, 'rev-parse', 'HEAD') && !git(target, 'status', '--porcelain=v1'));
  check('main retains newer feature and selected source work only', readFileSync(join(target, 'current.txt'), 'utf8') === 'newer main feature\n' && readFileSync(join(target, 'part.txt'), 'utf8') === 'palette\n' && !git(target, 'ls-tree', '-r', '--name-only', 'HEAD').includes('unselected.txt'));
  check('original source survives final integration unchanged', git(source, 'rev-parse', 'HEAD') === sourceBefore[0] && git(source, 'status', '--porcelain=v1') === sourceBefore[1]);
  const finalReload = new IntegrationService(store, projects, () => sessions, data);
  check('completed receipt survives restart without reapplying', (await finalReload.query({ operation: 'report', integrationId: prepared.id }, 'desktop')).report?.integratedCommit === integrated.integratedCommit);

  assertIpcPayload('integration:query', { operation: 'report', integrationId: prepared.id });
  assertIpcPayload('integration:command', { operation: 'integrate', integrationId: prepared.id, revision: retested.revision, message: 'approved' });
  check('dedicated IPC is classified without widening remote generic commands', CHANNEL_POLICY['integration:command'].effect === 'launch'
    && CHANNEL_POLICY['integration:command'].surface === 'desktop' && !REMOTE_COMMAND_CHANNELS.includes('integration:command'));
  await refuses('IPC rejects hidden command payloads', () => assertIpcPayload('integration:command', { operation: 'test', integrationId: prepared.id, argv: ['evil'] }), /invalid/);
  linkSync(join(source, 'local.txt'), join(root, 'hardlink.txt'));
  await refuses('linked source files fail closed before preview', () => preview(), /verknüpft/); unlinkSync(join(root, 'hardlink.txt'));

  writeFileSync(join(target, 'part.txt'), 'new main palette\n'); git(target, 'add', '.'); git(target, 'commit', '-m', 'main advanced again');
  writeFileSync(join(source, 'part.txt'), 'old experimental palette\n');
  const { application: app, devices } = fixture;
  devices.enroll('tablet', 'Tablet', 'd'.repeat(40)); devices.setAdminScopes('tablet', ['workspace:read', 'repositories:write', 'terminal:control']);
  const context = (): RemoteCommandContext => ({ principal: { id: 'tablet', kind: 'device', proof: 'device-signature', scopes: new Set(devices.activeDevices()[0]!.scopes) }, idempotencyKey: randomUUID(), requestId: 'integration' });
  const apiPreview = () => app.integration(context(), { operation: 'preview', repositoryId: 'repo', sourceId: list[0]!.id }, false);
  const conflictPreview = (await apiPreview()).preview!;
  check('API reports double-modified files for review', conflictPreview.files.some((file) => file.path === 'part.txt' && file.assessment === 'review'));
  const prepareCommand = { operation: 'prepare', previewId: conflictPreview.id, paths: ['part.txt'] };
  await refuses('API requires a signed device', () => app.integration({ ...context(), principal: { kind: 'bootstrap-token', id: 'bearer', proof: 'bearer', scopes: new Set(['read']) } }, { operation: 'sources', repositoryId: 'repo' }, false), /device_proof_required/);
  await refuses('API requires idempotency for prepare', () => app.integration({ ...context(), idempotencyKey: undefined }, prepareCommand, true), /idempotency_key_required/);
  devices.setAdminScopes('tablet', ['workspace:read', 'repositories:write'], { mode: 'selected', repositoryIds: ['repo'], agentIds: ['builder'] });
  await refuses('partial resource access cannot disclose other worktrees', () => apiPreview(), /scope_not_granted/);
  devices.setAdminScopes('tablet', ['workspace:read', 'repositories:write'], { mode: 'all' });
  const ctx = context(); const conflict = (await app.integration(ctx, prepareCommand, true)).report!;
  check('conflicts remain in separate copy and never alter main', conflict.files.some((file) => file.path === 'part.txt' && file.conflict) && readFileSync(join(target, 'part.txt'), 'utf8') === 'new main palette\n');
  check('replayed preparation returns same durable review', (await app.integration(ctx, prepareCommand, true)).replayed === true);
  await refuses('test start additionally requires terminal capability', () => app.integration(context(), { operation: 'test', integrationId: conflict.id }, true), /scope_not_granted/);
  devices.setAdminScopes('tablet', ['workspace:read', 'repositories:write', 'terminal:control']);
  await refuses('unresolved conflicts cannot pass test admission', () => app.integration(context(), { operation: 'test', integrationId: conflict.id }, true), /Konflikte/);
  const conflictPath = store.get().projectWorkspaces.find((item) => item.id === conflict.workspaceId)!.workspaceDir;
  writeFileSync(join(conflictPath, 'part.txt'), 'resolved palette with new feature\n');
  const resolution = await fixture.projectGit.preview(conflict.workspaceId!, { kind: 'resolve', paths: ['part.txt'] }, 'desktop');
  await fixture.projectGit.apply(resolution.id, 'desktop');
  check('existing Git UI service can resolve integration conflicts', !(await app.integration(context(), { operation: 'report', integrationId: conflict.id }, false)).report!.files.some((file) => file.conflict));
  const revoked = context(); devices.setAdminScopes('tablet', ['workspace:read']);
  await refuses('revocation invalidates captured device principal', () => app.integration(revoked, { operation: 'test', integrationId: conflict.id }, true), /scope_not_granted/);
  devices.setAdminScopes('tablet', ['workspace:read', 'repositories:write', 'terminal:control']);
  await app.integration(context(), { operation: 'test', integrationId: conflict.id }, true);
  let report = (await app.integration(context(), { operation: 'report', integrationId: conflict.id }, false)).report!;
  const until = Date.now() + 60_000;
  while (report.phase === 'testing' && Date.now() < until) { await new Promise((resolve) => setTimeout(resolve, 100)); report = (await app.integration(context(), { operation: 'report', integrationId: conflict.id }, false)).report!; }
  check('resolved conflict can acquire positive test proof through API', report.tested);
  writeFileSync(join(target, 'later.txt'), 'uncommitted target');
  await refuses('target changes after tests block final approval', () => app.integration(context(), { operation: 'integrate', integrationId: conflict.id, revision: report.revision, message: 'resolved palette' }, true), /gültige Freigabe/);
  unlinkSync(join(target, 'later.txt'));
  const finalContext = context(); const confirm = { operation: 'integrate', integrationId: conflict.id, revision: report.revision, message: 'resolved palette' };
  const approved = await app.integration(finalContext, confirm, true);
  check('final API positive control integrates conflict resolution', approved.report?.phase === 'integrated' && readFileSync(join(target, 'part.txt'), 'utf8') === 'resolved palette with new feature\n');
  check('final approval replay cannot create duplicate commits', (await app.integration(finalContext, confirm, true)).replayed === true && git(target, 'rev-parse', 'HEAD') === approved.report!.integratedCommit);
  const brokenData = join(root, 'broken-reviews'); mkdirSync(brokenData); writeFileSync(join(brokenData, 'reviews.json'), '{broken');
  const broken = new IntegrationService(store, projects, () => sessions, brokenData);
  await refuses('corrupt review storage fails closed and preserves bytes', () => broken.query({ operation: 'sources', repositoryId: 'repo' }, 'desktop'), /nicht verfügbar/);
  check('corrupt original remains untouched', readFileSync(join(brokenData, 'reviews.json'), 'utf8') === '{broken');
  const recoveryData = join(root, 'recovery-reviews'); mkdirSync(recoveryData);
  const recovered = JSON.parse(readFileSync(join(data, 'reviews.json'), 'utf8'));
  recovered.records[0].report.phase = 'testing'; recovered.records[0].report.checks[0].status = 'running';
  writeFileSync(join(recoveryData, 'reviews.json'), JSON.stringify(recovered));
  const recovery = new IntegrationService(store, projects, () => sessions, recoveryData);
  const interrupted = (await recovery.query({ operation: 'report', integrationId: prepared.id }, 'desktop')).report!;
  check('restart invalidates interrupted test proof and marks unfinished checks', interrupted.phase === 'interrupted' && !interrupted.tested && interrupted.checks[0]!.status === 'failed' && interrupted.checkNotice.includes('Neustart'));
  const injectedData = join(root, 'injected-reviews'); mkdirSync(injectedData);
  recovered.records[0].report.hiddenHostPath = root; writeFileSync(join(injectedData, 'reviews.json'), JSON.stringify(recovered));
  const injected = new IntegrationService(store, projects, () => sessions, injectedData);
  await refuses('unknown persisted fields cannot reach a wire report', () => injected.query({ operation: 'report', integrationId: prepared.id }, 'desktop'), /nicht verfügbar/);
  console.log(`\nIntegration workflow: ${passed} passed, 0 failed`);
})().catch((error) => { console.error(error); console.error('Fixture retained:', root); process.exitCode = 1; });
