/** Guided first setup through the production Electron UI and isolated native CLIs. */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { _electron as electron, type ElectronApplication, type Page } from 'playwright';
import { writeModelCliFixtures, MODEL_FIXTURE_CATALOG } from './fixtures/model-clis';

let passed = 0; let failed = 0;
const check = (name: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${name}`); } else { failed++; console.error(`FAIL  ${name}`); } };
const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-setup-electron-')));
const evidence = resolve('test-results/setup'); mkdirSync(evidence, { recursive: true });
let app: ElectronApplication | undefined; let page: Page | undefined;
void (async () => {
  if (process.platform !== 'win32') throw new Error('Setup flow is currently measured on native Windows');
  const cli = writeModelCliFixtures(root); const projects = join(root, 'projects'); const repo = join(projects, 'Erstes Projekt'); mkdirSync(repo, { recursive: true });
  execFileSync('git', ['init', '--initial-branch=main', repo], { windowsHide: true });
  writeFileSync(join(repo, 'AGENTS.md'), '# Existing project instructions\n');
  execFileSync('git', ['-C', repo, 'add', 'AGENTS.md'], { windowsHide: true });
  execFileSync('git', ['-C', repo, '-c', 'user.name=Fixture', '-c', 'user.email=fixture@localhost', '-c', 'commit.gpgSign=false', 'commit', '-m', 'Existing project'], { windowsHide: true });
  const failureMarker = join(root, 'fail-diagnostics'); const launcher = join(root, 'launch.cjs');
  writeFileSync(launcher, `const {ipcMain}=require('electron'); const fs=require('node:fs'); const handle=ipcMain.handle.bind(ipcMain);
ipcMain.handle=(channel, listener)=>handle(channel,(...args)=>{if(channel==='harness:diagnose'&&fs.existsSync(${JSON.stringify(failureMarker)}))throw new Error('Isolated diagnostic failure');return listener(...args);});
require(${JSON.stringify(resolve('out/main/index.js'))});`);
  const env = { ...process.env, Path: `${cli.bin};${process.env.Path ?? process.env.PATH}`, ADE_USER_DATA_DIR: join(root, 'profile'), ADE_HOST_API_ENABLED: '0', NODE_ENV: 'test' };
  for (const key of ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'XAI_API_KEY', 'GOOGLE_API_KEY', 'GEMINI_API_KEY']) delete (env as Record<string, string | undefined>)[key];
  app = await electron.launch({ args: [launcher], cwd: resolve('.'), env });
  page = await app.firstWindow(); page.setDefaultTimeout(30_000); const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.getByRole('heading', { name: 'Willkommen in ADE', exact: true }).waitFor();
  check('empty desktop offers project setup without a category', await page.getByRole('button', { name: 'ADE jetzt einrichten', exact: true }).isVisible());
  await page.getByRole('button', { name: 'ADE jetzt einrichten', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'ADE einrichten', exact: true });
  check('setup receives focus and exposes four explicit steps', await dialog.evaluate((node) => node.contains(document.activeElement)) && await dialog.getByRole('navigation', { name: 'Einrichtungsschritte' }).getByRole('button').count() === 4);
  const path = dialog.getByRole('textbox', { name: 'Projekt-Stammordner', exact: true }); await path.fill(join(repo, 'AGENTS.md'));
  await dialog.getByRole('button', { name: 'Projektstart speichern', exact: true }).click(); await dialog.getByRole('alert').waitFor();
  check('invalid project root is rejected without claiming completion', !(await page.evaluate(() => window.ade.invoke('projectDefaults:get'))).configured);
  await path.fill(projects); await dialog.getByRole('button', { name: 'Projektstart speichern', exact: true }).click();
  await dialog.getByRole('status').filter({ hasText: 'Projektstart gespeichert' }).waitFor();
  check('saving the root needs no agent identity', (await page.evaluate(() => window.ade.invoke('projectDefaults:get'))).rootPath === projects && (await page.evaluate(() => window.ade.invoke('config:get'))).agents.length === 0);
  await dialog.getByRole('button', { name: 'Weiter', exact: true }).focus(); await page.keyboard.press('Enter');
  await dialog.getByRole('button', { name: 'CLI-Status erneut prüfen', exact: true }).waitFor();
  const readiness = dialog.getByRole('region', { name: 'CLI-Bereitschaft' });
  check('native CLI status is measured without an agent', (await readiness.innerText()).includes('9.9.9 fixture') && await readiness.getByText('Angemeldet', { exact: true }).count() >= 1);
  check('keyboard step navigation focuses its heading', await dialog.getByRole('heading', { name: 'CLI prüfen', exact: true }).evaluate((node) => node === document.activeElement));
  writeFileSync(cli.state, JSON.stringify({ ...MODEL_FIXTURE_CATALOG, signedOut: true, grokUnavailable: true }));
  await readiness.getByRole('button', { name: 'CLI-Status erneut prüfen', exact: true }).click();
  await readiness.getByText('Anmeldung fehlt', { exact: true }).first().waitFor();
  check('signed-out status replaces earlier authenticated status', await readiness.getByText('Anmeldung fehlt', { exact: true }).count() >= 2 && !await readiness.getByText('Angemeldet', { exact: true }).count());
  writeFileSync(failureMarker, 'fail');
  await readiness.getByRole('button', { name: 'CLI-Status erneut prüfen', exact: true }).click(); await readiness.getByRole('alert').waitFor();
  check('failed probe is explicit and clears stale readiness', !await readiness.getByRole('list').count() && (await readiness.getByRole('alert').innerText()).includes('Erneut prüfen'));
  rmSync(failureMarker); writeFileSync(cli.state, JSON.stringify(MODEL_FIXTURE_CATALOG));
  await readiness.getByRole('button', { name: 'CLI-Status erneut prüfen', exact: true }).click(); await readiness.getByText('Angemeldet', { exact: true }).first().waitFor();
  check('positive retry restores measured CLI status', await readiness.getByRole('listitem').count() === 3);
  await page.screenshot({ path: join(evidence, '25-desktop-setup.png') });
  await dialog.getByRole('button', { name: '4. Freigaben prüfen', exact: true }).click();
  await dialog.getByText('Noch keine Geräte verbunden.', { exact: false }).waitFor();
  check('unpaired state explains explicit grants without activating remote access', !(await page.evaluate(() => window.ade.invoke('mobileAccess:status'))).enabled && (await page.evaluate(() => window.ade.invoke('remoteDevices:list'))).devices.length === 0);
  await page.keyboard.press('Escape');
  check('closing setup returns focus to its original entry', await page.getByRole('button', { name: 'ADE jetzt einrichten', exact: true }).evaluate((node) => node === document.activeElement));
  await page.getByRole('button', { name: 'Einrichtung', exact: true }).click();
  check('saved root survives reopening setup', await dialog.getByRole('textbox', { name: 'Projekt-Stammordner', exact: true }).inputValue() === projects);
  await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]!.setSize(720, 820); });
  check('setup remains within a narrow desktop viewport', await dialog.evaluate((node) => node.getBoundingClientRect().right <= innerWidth && node.scrollWidth <= node.clientWidth));
  await dialog.getByRole('button', { name: 'Zu den Projekten', exact: true }).click();
  check('setup exits to Projects with a stable focus target', await page.getByRole('tab', { name: 'Projekte view', exact: true }).evaluate((node) => node === document.activeElement));
  await page.getByRole('button', { name: 'Workspace öffnen: Erstes Projekt', exact: true }).click();
  const terminal = page.getByRole('region', { name: 'Projekt-Terminal', exact: true }); await terminal.getByLabel('Projekt-CLI', { exact: true }).selectOption('shell');
  await terminal.getByRole('button', { name: 'Leeres Terminal öffnen', exact: true }).click();
  await terminal.getByLabel('CLI- und Terminalstatus', { exact: true }).waitFor();
  const config = await page.evaluate(() => window.ade.invoke('config:get')); const { sessions } = await page.evaluate(() => window.ade.invoke('pty:list'));
  check('first real project shell uses the selected checkout without creating a profile', config.agents.length === 0 && config.categories.length === 0 && sessions.some((session) => session.workspaceDir === repo && !session.agentId));
  check('setup preserves original repository instructions and has no renderer errors', readFileSync(join(repo, 'AGENTS.md'), 'utf8') === '# Existing project instructions\n' && errors.length === 0);
})().catch(async (error) => { failed++; console.error(error); await page?.screenshot({ path: join(evidence, 'failure.png') }).catch(() => undefined); }).finally(async () => {
  await app?.close().catch(() => undefined);
  if (dirname(resolve(root)) !== realpathSync.native(tmpdir()) || !basename(root).startsWith('ade-setup-electron-')) throw new Error('Unexpected setup fixture cleanup root');
  rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
  console.log(`Setup Electron: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
});
