import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { _electron as electron, type ElectronApplication, type Page } from 'playwright';
import { expect } from 'playwright/test';
import { newOrganizerDocument } from '../src/shared/organizer';
import { randomUUID } from 'node:crypto';
const root = realpathSync.native(mkdtempSync(join(tmpdir(), 'ade-organizer-electron-')));
const evidence = resolve('test-results/organizer'); mkdirSync(evidence, { recursive: true });
let app: ElectronApplication | undefined; let page: Page | undefined; let passed = 0; let failed = 0;
const check = (name: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${name}`); } else { failed++; console.error(`FAIL  ${name}`); } };
void (async () => {
  const launcher = join(root, 'launch.cjs');
  writeFileSync(launcher, `require(${JSON.stringify(resolve('scripts/fixtures/conversation-speech.cjs'))});require(${JSON.stringify(resolve(process.env.ADE_ORGANIZER_MAIN ?? 'out/main/index.js'))});`);
  app = await electron.launch({ args: [launcher, '--use-fake-device-for-media-stream'], env: { ...process.env, ADE_USER_DATA_DIR: join(root, 'profile'), ADE_HOST_API_ENABLED: '0', NODE_ENV: 'test' } });
  page = await app.firstWindow(); page.setDefaultTimeout(20_000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('tab', { name: 'Notizen', exact: true }).click();
  await page.getByRole('button', { name: 'Neue Notiz', exact: true }).click();
  await page.getByLabel('Titel', { exact: true }).fill('Desktop-Skizze'); await page.getByLabel('Notiztext', { exact: true }).fill('Gespeichert über IPC');
  await expect.poll(async () => { const result = await page!.evaluate(() => window.ade.invoke('organizer:query', { operation: 'list' })); return 'index' in result && result.index.entries.some(item => item.title === 'Desktop-Skizze'); }).toBe(true);
  check('desktop StrictMode editor persists through the sandboxed preload bridge', true);
  await page.reload(); await page.getByRole('button', { name: /Desktop-Skizze/ }).click();
  check('desktop document reload retains text', await page.getByLabel('Notiztext', { exact: true }).inputValue() === 'Gespeichert über IPC');
  check('with a mouse the title takes focus so typing can start at once', await page.getByLabel('Titel', { exact: true }).evaluate((node) => node === window.document.activeElement));
  await page.getByRole('button', { name: 'Zeichnen', exact: true }).click(); const sheet = page.getByRole('dialog', { name: 'Skizze', exact: true }); await sheet.waitFor();
  check('desktop sheet opens full-window with the drawing surface focused', await sheet.locator('canvas').evaluate(node => node === window.document.activeElement) && await sheet.locator('output.sketch-sheet-zoom-level').textContent() === '100 %');
  await page.waitForTimeout(300); await page.screenshot({ path: join(evidence, 'desktop-sheet.png') });
  await page.keyboard.press('Escape'); await sheet.waitFor({ state: 'hidden' });
  check('desktop sheet closes with Escape and returns focus to Draw', await page.getByRole('button', { name: 'Zeichnen', exact: true }).evaluate(node => node === window.document.activeElement));
  await page.evaluate(() => window.ade.invoke('harness:setServiceKey', { name: 'ELEVENLABS_API_KEY', value: 'conversation-speech-fixture', scope: 'all' }));
  await page.getByRole('button', { name: 'Diktat', exact: true }).click(); await page.getByRole('button', { name: 'Text diktieren', exact: true }).click();
  await expect(page.getByLabel('Diktatvorschau', { exact: true })).toHaveValue('Wo stehen meine Projekte heute?');
  check('organizer microphone produces a preview without changing the note', await page.getByLabel('Notiztext', { exact: true }).inputValue() === 'Gespeichert über IPC');
  await page.getByLabel('Notiztext', { exact: true }).fill('Während Diktat ergänzt');
  await page.getByRole('button', { name: 'Aufnahme stoppen', exact: true }).click(); await page.getByText('Diktat abgeschlossen. Text prüfen und übernehmen.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Diktat übernehmen', exact: true }).click();
  await expect(page.getByLabel('Notiztext', { exact: true })).toHaveValue('Während Diktat ergänzt\nWo stehen meine Projekte heute?');
  await expect(page.getByLabel('Diktatvorschau', { exact: true })).toHaveCount(0);
  check('dictation appends to the current note before consuming its preview', true);
  await page.getByLabel('Notiztext', { exact: true }).fill('x'.repeat(32_000));
  await page.getByRole('button', { name: 'Text diktieren', exact: true }).click();
  await expect(page.getByLabel('Diktatvorschau', { exact: true })).toHaveValue('Wo stehen meine Projekte heute?');
  await page.getByRole('button', { name: 'Aufnahme stoppen', exact: true }).click(); await page.getByText('Diktat abgeschlossen. Text prüfen und übernehmen.', { exact: true }).waitFor();
  check('full note keeps a copyable transcript and blocks a lossy append', await page.getByRole('button', { name: 'Diktat übernehmen', exact: true }).isDisabled());
  await page.getByRole('button', { name: 'Diktat verwerfen', exact: true }).click(); await page.getByLabel('Notiztext', { exact: true }).fill('Gespeichert über IPC');
  await expect.poll(async () => { const value = await page!.evaluate(() => new Promise<boolean>((done, reject) => { const request = indexedDB.open('ade-organizer-v1'); request.onerror = () => reject(request.error); request.onsuccess = () => {
    const db = request.result; const read = db.transaction('profiles').objectStore('profiles').get('desktop'); read.onsuccess = () => { const entries = read.result.entries; db.close(); done(entries.some((entry: { draft?: { text: string }; base?: { document: { text: string } } }) => (entry.draft ?? entry.base?.document)?.text === 'Gespeichert über IPC')); };
  } })); return value; }).toBe(true);
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof original>) { if ((window as unknown as { failOrganizerSave?: boolean }).failOrganizerSave && this.name === 'profiles') throw new DOMException('Speicher-Test: kein Platz', 'QuotaExceededError'); return original.apply(this, args); };
    (window as unknown as { failOrganizerSave: boolean }).failOrganizerSave = true;
  });
  await page.getByLabel('Notiztext', { exact: true }).fill('Nur im offenen Editor erhalten'); await page.getByRole('alert').filter({ hasText: 'Speicher-Test: kein Platz' }).waitFor();
  await page.getByRole('tab', { name: 'Aufgaben', exact: true }).click(); await page.getByRole('tab', { name: 'Notizen', exact: true }).click(); await page.getByRole('button', { name: /Desktop-Skizze/ }).click();
  check('real IndexedDB quota failure preserves the editor across page changes', await page.getByLabel('Notiztext', { exact: true }).inputValue() === 'Nur im offenen Editor erhalten');
  await page.evaluate(() => { (window as unknown as { failOrganizerSave: boolean }).failOrganizerSave = false; });
  await page.getByRole('button', { name: 'Speichern erneut versuchen', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Speichern erneut versuchen', exact: true })).toHaveCount(0);
  await page.reload(); await page.getByRole('button', { name: /Desktop-Skizze/ }).click();
  check('positive recovery persists the retained draft through renderer reload', await page.getByLabel('Notiztext', { exact: true }).inputValue() === 'Nur im offenen Editor erhalten');
  const document = newOrganizerDocument('task'); document.title = 'Private Erinnerung'; document.reminderAt = Date.now() - 1000;
  await page.evaluate(input => window.ade.invoke('organizer:command', input), { operation: 'put' as const, writerId: randomUUID(), sequence: 1, baseRevision: 0, document });
  await page.getByRole('complementary', { name: 'Fällige Aufgaben', exact: true }).waitFor();
  check('due reminder is visible while another page is open', await page.getByText('1 Erinnerung(en) fällig.', { exact: true }).isVisible());
  await page.getByRole('button', { name: 'Aufgaben öffnen', exact: true }).click(); await page.getByRole('button', { name: /Private Erinnerung/ }).click();
  await page.getByRole('button', { name: 'Erinnerung bestätigen', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Fällige Aufgaben', exact: true })).toHaveCount(0);
  check('acknowledging a reminder clears the global reminder after durable save', true);
  const deleted = page.getByRole('button', { name: 'Eintrag löschen', exact: true }); await deleted.click();
  const dialog = page.getByRole('dialog', { name: 'Eintrag löschen', exact: true }); await dialog.waitFor();
  check('destructive-action dialog receives focus', await dialog.evaluate(node => node.contains(window.document.activeElement)));
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  check('closing the dialog restores its opener', await deleted.evaluate(node => node === window.document.activeElement));
  await page.getByRole('tab', { name: 'Graph', exact: true }).click();
  await page.getByRole('group', { name: 'Run', exact: true }).waitFor();
  check('empty Graph has grouped controls and one New Run entry', await page.getByRole('button', { name: 'Neuer Run', exact: true }).count() === 1
    && await page.getByRole('group', { name: 'Ansicht', exact: true }).isVisible());
  await page.evaluate(async () => {
    const category = await window.ade.invoke('category:create', { name: 'Organizer test' });
    const agent = await window.ade.invoke('agent:create', { name: 'Fixture agent', categoryId: category.id, runtime: 'codex', permissionMode: 'default' });
    await window.ade.invoke('run:create', { name: 'Graph-Gruppen', repositoryId: null, participants: [{ agentId: agent.id, role: 'orchestrator' }] });
  });
  await page.getByRole('group', { name: 'Run-Steuerung für Graph-Gruppen', exact: true }).waitFor();
  check('active graph separates run controls, results and administration without duplicate creation', await page.getByRole('button', { name: 'Neuer Run', exact: true }).count() === 1
    && await page.getByRole('group', { name: 'Ergebnisse', exact: true }).isVisible());
  await page.screenshot({ path: join(evidence, 'desktop-graph.png') });
  await page.getByRole('button', { name: 'Navigation einklappen', exact: true }).click(); await page.reload();
  await page.getByRole('button', { name: 'Navigation ausklappen', exact: true }).waitFor();
  check('desktop grouped navigation remains collapsed after reload', true);
  await page.getByRole('button', { name: 'Navigation ausklappen', exact: true }).click();
  await page.getByRole('tab', { name: 'Notizen', exact: true }).click(); await page.getByRole('button', { name: /Desktop-Skizze/ }).click();
  await page.screenshot({ path: join(evidence, 'desktop-note.png') });
  check('desktop personal workflow has no uncaught renderer errors', errors.length === 0);
})().catch(async error => { failed++; console.error(error); await page?.screenshot({ path: join(evidence, 'desktop-failure.png') }).catch(() => undefined); }).finally(async () => {
  await app?.close(); if (dirname(root) !== realpathSync.native(tmpdir())) throw new Error('Unexpected Electron fixture root');
  rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); console.log(`Organizer Electron: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
});
