import { execFileSync } from 'node:child_process';
import { existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createRemoteWorkspaceFixture } from './helpers/remoteWorkspaceFixture';
import { ProjectGitService } from '../src/main/repositories/ProjectGitService';
import { validProjectGitAction } from '../src/shared/projectGit';
import { RemoteApiError, type RemoteCommandContext } from '../src/main/application/AdeApplicationService';
import { assertIpcPayload } from '../src/main/ipcValidation';

let passed = 0; let failed = 0;
const check = (label: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${label}`); } else { failed++; console.error(`FAIL  ${label}`); } };
async function rejects(label: string, action: () => unknown) { try { await action(); check(label, false); } catch { check(label, true); } }
const root = mkdtempSync(join(tmpdir(), 'ade-project-git-'));
void (async () => {
  const f = createRemoteWorkspaceFixture(root); f.devices.enroll('tablet', 'Tablet', 't'.repeat(40)); f.devices.setAdminScopes('tablet', ['catalog:write', 'workspace:read', 'projects:write']);
  const context = (): RemoteCommandContext => ({ principal: { id: 'tablet', kind: 'device', proof: 'device-signature', scopes: new Set(f.devices.activeDevices()[0]!.scopes) }, requestId: 'git-fixture', idempotencyKey: randomUUID() });
  const repoResult = await f.application.administer(context(), { operation: 'project-create', input: { name: 'Git work' } });
  const entry = (await f.projects.directory()).entries.find((item) => item.repositoryId === repoResult.created!.id)!;
  const workspace = await f.projects.open(entry.id); const cwd = (await f.projects.resolve(workspace.id)).workspace.workspaceDir;
  const gitAt = (path: string, ...args: string[]) => execFileSync('git', ['-C', path, '-c', 'commit.gpgSign=false', ...args], { encoding: 'utf8', windowsHide: true });
  const git = (...args: string[]) => gitAt(cwd, ...args); const write = (name: string, value: string) => writeFileSync(join(cwd, name), value);
  git('config', 'user.name', 'ADE fixture'); git('config', 'user.email', 'fixture@example.invalid'); git('config', 'core.autocrlf', 'false');
  write('a.txt', 'base\n'); write('b.txt', 'base\n'); git('add', '.'); git('commit', '-m', 'base');
  let now = Date.now(); const service = new ProjectGitService(f.store, f.projects, () => f.sessions, () => now);
  const view = () => service.overview(workspace.id);
  const apply = async (action: Parameters<ProjectGitService['preview']>[1]) => service.apply((await service.preview(workspace.id, action, 'desktop')).id, 'desktop');
  check('initial overview reports actual clean main checkout', (await view()).workspace.branch === 'main' && !(await view()).files.length);
  check('actions reject arbitrary command, host path and duplicate selections', !validProjectGitAction({ kind: 'commit', paths: ['a.txt'], message: 'x', command: 'bad' })
    && !validProjectGitAction({ kind: 'commit', paths: ['C:/bad'], message: 'x' }) && !validProjectGitAction({ kind: 'resolve', paths: ['a', 'a'] }));
  write('a.txt', 'selected change\n'); write('b.txt', 'staged elsewhere\n'); git('add', 'b.txt');
  const before = git('rev-parse', 'HEAD').trim(); const commit = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'selected a' }, 'desktop');
  check('commit preview includes exact selection without mutation', commit.affected.join() === 'a.txt' && git('rev-parse', 'HEAD').trim() === before);
  const diff = await service.diff(workspace.id, 'a.txt'); check('diff shows selected change with no host paths', diff.text.includes('+selected change') && !JSON.stringify(diff).includes(cwd));
  await service.apply(commit.id, 'desktop');
  check('selective commit includes only selected file', git('show', 'HEAD:a.txt') === 'selected change\n' && git('show', 'HEAD:b.txt') === 'base\n');
  check('selective commit preserves unrelated staged and working changes', git('diff', '--cached', '--name-only').trim() === 'b.txt' && readFileSync(join(cwd, 'b.txt'), 'utf8') === 'staged elsewhere\n');
  await rejects('applied preview cannot execute twice', () => service.apply(commit.id, 'desktop'));
  await apply({ kind: 'commit', paths: ['b.txt'], message: 'save b' });
  write('a.txt', 'first draft\n'); const stale = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'draft' }, 'desktop');
  write('a.txt', 'changed after preview\n');
  await rejects('same porcelain status with changed content invalidates commit preview', () => service.apply(stale.id, 'desktop'));
  check('rejected drift preserves edited file', readFileSync(join(cwd, 'a.txt'), 'utf8') === 'changed after preview\n');
  const owned = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'draft' }, 'desktop');
  await rejects('another principal cannot use the preview', () => service.apply(owned.id, 'other'));
  now += 300_001; await rejects('expired preview cannot commit', () => service.apply(owned.id, 'desktop')); now = Date.now();
  const denied = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'draft' }, 'desktop');
  await rejects('revocation before mutation prevents commit', () => service.apply(denied.id, 'desktop', () => { throw new Error('revoked'); }));
  f.sessions.push({ id: 'live', projectWorkspaceId: workspace.id, repositoryId: workspace.repositoryId, workspaceDir: cwd, branch: 'main', title: 'Shell', kind: 'interactive', status: 'running', createdAt: 1 });
  check('live terminal is visible as a Git blocker', (await view()).blockedReason?.includes('Terminalsitzung') === true);
  await rejects('live shell blocks commit preparation', () => service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'blocked' }, 'desktop'));
  f.sessions.length = 0; await apply({ kind: 'commit', paths: ['a.txt'], message: 'checked draft' });
  write('a.txt', 'index drift test\n'); write('b.txt', 'index drift sibling\n');
  const changedIndex = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'index test' }, 'desktop');
  git('add', 'b.txt'); await rejects('changed staging index invalidates preview', () => service.apply(changedIndex.id, 'desktop'));
  const changedHead = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'head test' }, 'desktop');
  git('commit', '-m', 'external staged b'); await rejects('external HEAD movement invalidates preview', () => service.apply(changedHead.id, 'desktop'));
  const laterSession = await service.preview(workspace.id, { kind: 'commit', paths: ['a.txt'], message: 'session race' }, 'desktop');
  f.sessions.push({ id: 'late', projectWorkspaceId: workspace.id, repositoryId: workspace.repositoryId, workspaceDir: cwd, branch: 'main', title: 'Shell', kind: 'interactive', status: 'running', createdAt: 1 });
  await rejects('terminal opened after preview prevents actual mutation', () => service.apply(laterSession.id, 'desktop'));
  f.sessions.length = 0; await apply({ kind: 'commit', paths: ['a.txt'], message: 'finish drift tests' });
  const hook = join(cwd, '.git', 'hooks', 'post-commit'); mkdirSync(dirname(hook), { recursive: true }); writeFileSync(hook, '#!/bin/sh\necho bad > hook-ran.txt\n', { mode: 0o755 });
  write('[literal].txt', 'one\n'); write('l.txt', 'other\n');
  await apply({ kind: 'commit', paths: ['[literal].txt'], message: 'literal selection' });
  check('literal path selection cannot include a matching glob sibling', git('ls-tree', '--name-only', 'HEAD').includes('[literal].txt') && !git('ls-tree', '--name-only', 'HEAD').split('\n').includes('l.txt'));
  check('commit never runs repository hooks', !existsSync(join(cwd, 'hook-ran.txt')));
  await apply({ kind: 'commit', paths: ['l.txt'], message: 'save sibling' });
  write('.env', 'TOKEN=private_value\n');
  check('protected file is explicitly unavailable for Git selection', (await view()).files.find((file) => file.path === '.env')?.selectable === false);
  await rejects('protected file diff fails closed', () => service.diff(workspace.id, '.env'));
  await rejects('protected file cannot be selected for a commit', () => service.preview(workspace.id, { kind: 'commit', paths: ['.env'], message: 'bad' }, 'desktop'));
  rmSync(join(cwd, '.env'));
  writeFileSync(join(root, 'linked-source.txt'), 'outside\n'); linkSync(join(root, 'linked-source.txt'), join(cwd, 'linked.txt'));
  check('hardlinked worktree file cannot enter a preview', (await view()).files.find((file) => file.path === 'linked.txt')?.selectable === false);
  rmSync(join(cwd, 'linked.txt'));
  git('switch', '-c', 'feature/conflict'); write('a.txt', 'feature\n'); git('add', 'a.txt'); git('commit', '-m', 'feature');
  git('switch', 'main'); write('a.txt', 'main\n'); git('add', 'a.txt'); git('commit', '-m', 'main');
  // Fixture commits use normal Git above; remove their deliberately executed hook artifact.
  if (existsSync(join(cwd, 'hook-ran.txt'))) rmSync(join(cwd, 'hook-ran.txt'));
  const mergePreview = await service.preview(workspace.id, { kind: 'merge', ref: 'refs/heads/feature/conflict' }, 'desktop');
  check('merge preview exposes pinned target SHA and changed files', !!mergePreview.targetHead && mergePreview.affected.includes('a.txt'));
  const conflict = await service.apply(mergePreview.id, 'desktop');
  check('merge reports actual conflicts and keeps them for resolution', conflict.merge && conflict.files.some((file) => file.path === 'a.txt' && file.conflict));
  await rejects('continue refuses unresolved index entries', () => service.preview(workspace.id, { kind: 'continue' }, 'desktop'));
  await rejects('resolution refuses conflict markers still in the file', () => service.preview(workspace.id, { kind: 'resolve', paths: ['a.txt'] }, 'desktop'));
  write('a.txt', 'combined resolution\n'); const resolved = await apply({ kind: 'resolve', paths: ['a.txt'] });
  check('explicit resolution stages the edited conflict without committing', resolved.merge && !resolved.files.some((file) => file.conflict));
  const finished = await apply({ kind: 'continue' });
  check('continue creates a real merge commit and clears the merge state', !finished.merge && git('rev-list', '--parents', '-n', '1', 'HEAD').trim().split(' ').length === 3 && git('show', 'HEAD:a.txt') === 'combined resolution\n');
  git('switch', 'feature/conflict'); write('a.txt', 'feature again\n'); git('add', 'a.txt'); git('commit', '-m', 'another change'); git('switch', 'main');
  if (existsSync(join(cwd, 'hook-ran.txt'))) rmSync(join(cwd, 'hook-ran.txt'));
  const priorAbort = git('rev-parse', 'HEAD').trim(); await apply({ kind: 'merge', ref: 'refs/heads/feature/conflict' });
  const aborted = await apply({ kind: 'abort' });
  check('explicit abort restores pre-merge HEAD and checkout', !aborted.merge && git('rev-parse', 'HEAD').trim() === priorAbort && readFileSync(join(cwd, 'a.txt'), 'utf8') === 'combined resolution\n');
  const remote = join(root, 'remote.git'); const peer = join(root, 'peer'); mkdirSync(remote); gitAt(remote, 'init', '--bare');
  git('remote', 'add', 'origin', remote); git('push', 'origin', 'main'); gitAt(root, 'clone', '--branch', 'main', remote, peer);
  gitAt(peer, 'config', 'user.name', 'Fixture'); gitAt(peer, 'config', 'user.email', 'fixture@example.invalid'); writeFileSync(join(peer, 'remote.txt'), 'remote addition\n');
  gitAt(peer, 'add', 'remote.txt'); gitAt(peer, 'commit', '-m', 'remote addition'); gitAt(peer, 'push', 'origin', 'main');
  git('config', 'remote.origin.fetch', '+refs/heads/*:refs/heads/*');
  const beforeFetch = git('rev-parse', 'HEAD').trim(); const fetched = await apply({ kind: 'fetch', remote: 'origin' });
  check('fetch updates only remote tracking refs despite configured local refspec', git('rev-parse', 'HEAD').trim() === beforeFetch && fetched.refs.some((ref) => ref.ref === 'refs/remotes/origin/main' && ref.head !== beforeFetch) && fetched.fetchedAt !== null);
  const pulled = await apply({ kind: 'pull', remote: 'origin', ref: 'refs/remotes/origin/main' });
  check('pull performs only reviewed fast-forward on current branch', pulled.head === gitAt(peer, 'rev-parse', 'HEAD').trim() && readFileSync(join(cwd, 'remote.txt'), 'utf8') === 'remote addition\n');
  write('local.txt', 'local\n'); await apply({ kind: 'commit', paths: ['local.txt'], message: 'local divergence' });
  writeFileSync(join(peer, 'remote2.txt'), 'remote 2\n'); gitAt(peer, 'add', 'remote2.txt'); gitAt(peer, 'commit', '-m', 'remote divergence'); gitAt(peer, 'push', 'origin', 'main'); await apply({ kind: 'fetch', remote: 'origin' });
  await rejects('divergent pull fails without rebasing or resetting', () => service.preview(workspace.id, { kind: 'pull', remote: 'origin', ref: 'refs/remotes/origin/main' }, 'desktop'));
  git('remote', 'add', 'unsafe', 'ext::bad-helper');
  await rejects('remote helper transport is refused before fetch', () => service.preview(workspace.id, { kind: 'fetch', remote: 'unsafe' }, 'desktop'));
  git('remote', 'remove', 'unsafe');
  const mergedRemote = await apply({ kind: 'merge', ref: 'refs/remotes/origin/main' });
  check('nonconflicting divergent merge waits for explicit completion', mergedRemote.merge && !mergedRemote.files.some((file) => file.conflict));
  const final = await apply({ kind: 'continue' });
  check('final positive control has clean main, both deliveries and no merge state', !final.merge && !final.files.length && final.workspace.branch === 'main' && existsSync(join(cwd, 'local.txt')) && existsSync(join(cwd, 'remote2.txt')));
  async function deniedCode(label: string, action: () => unknown, code: string) { try { await action(); check(label, false); } catch (error) { check(label, error instanceof RemoteApiError && error.code === code); } }
  const remoteView = await f.application.queryProjects(context(), { operation: 'git', workspaceId: workspace.id });
  check('signed project read exposes path-free Git state without mutation rights', remoteView.git?.head === final.head && !JSON.stringify(remoteView).includes(cwd));
  write('api.txt', 'api commit\n');
  await deniedCode('project-open grant alone cannot preview Git mutations', () => f.application.queryProjects(context(), { operation: 'git-preview', workspaceId: workspace.id, action: { kind: 'commit', paths: ['api.txt'], message: 'API commit' } }), 'scope_not_granted');
  f.devices.setAdminScopes('tablet', ['workspace:read', 'workspace:write', 'projects:write', 'projectGit:write']);
  const apiPreview = (await f.application.queryProjects(context(), { operation: 'git-preview', workspaceId: workspace.id, action: { kind: 'commit', paths: ['api.txt'], message: 'API commit' } })).gitPreview!;
  const commandContext = context(); const apiCommand = { operation: 'git-apply', previewId: apiPreview.id };
  await deniedCode('Git apply requires an idempotency receipt', () => f.application.commandProject({ ...commandContext, idempotencyKey: undefined }, apiCommand), 'idempotency_key_required');
  const done = await f.application.commandProject(commandContext, apiCommand); const count = git('rev-list', '--count', 'HEAD');
  const replay = await f.application.commandProject(commandContext, apiCommand);
  check('signed Git replay does not create a second commit', !done.replayed && replay.replayed && git('rev-list', '--count', 'HEAD') === count && done.git?.head === replay.git?.head);
  write('api.txt', 'changed after success\n');
  check('replayed receipt reads current Git status rather than returning stale state', (await f.application.commandProject(commandContext, apiCommand)).git?.files.some((file) => file.path === 'api.txt') === true);
  f.devices.setAdminScopes('tablet', ['workspace:read', 'projects:write']);
  await deniedCode('revoked Git right prevents replay of an earlier success', () => f.application.commandProject(commandContext, apiCommand), 'scope_not_granted');
  await rejects('desktop file read rejects agent ownership and host paths', () => assertIpcPayload('project:fileRead', { projectWorkspaceId: workspace.id, path: 'C:/private', agentId: 'builder' }));
  await rejects('desktop file save rejects extra dispatch fields', () => assertIpcPayload('project:fileSave', { projectWorkspaceId: workspace.id, path: 'api.txt', text: 'x', revision: 'a'.repeat(64), workspaceVersion: 'a'.repeat(64), command: 'bad' }));
  await apply({ kind: 'commit', paths: ['api.txt'], message: 'final state' });
  check('final API and file-boundary positive control returns clean state', !(await view()).files.length);
  const scope = await f.projects.resolve(workspace.id);
  f.store.save({ runWorkspaceLeases: [{ id: 'git-lease', status: 'active', commonGitDir: scope.repository.commonGitDir,
    runId: 'run', participantId: 'participant', agentId: 'fixture', workspaceDir: join(root, 'another-checkout'), isRepo: true,
    branch: 'leased', baseSha: (await view()).head!, acquiredAt: 1 }] });
  await rejects('managed lease in another checkout blocks repository Git mutations', () => service.preview(workspace.id, { kind: 'fetch', remote: 'origin' }, 'desktop'));
  f.store.save({ runWorkspaceLeases: [] });
  check('released common-repository lease restores clean readable workspace', !(await view()).blockedReason && !(await view()).files.length);
})().catch((error) => { failed++; console.error(error); }).finally(() => {
  if (dirname(resolve(root)) !== resolve(tmpdir())) throw new Error('unexpected fixture root'); rmSync(root, { recursive: true, force: true });
  console.log(`Project Git: ${passed} passed, ${failed} failed`); process.exitCode = failed ? 1 : 0;
});
