import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { chromium, type Browser } from 'playwright';
import { createRemoteWorkspaceFixture } from './helpers/remoteWorkspaceFixture';
import { mobileTlsProxy } from './helpers/mobileBrowser';
import { BrowserSessions } from '../src/main/remote/BrowserSessions';
import { HostApiServer } from '../src/main/remote/HostApiServer';
import { RemoteAuthorizer } from '../src/main/remote/authorization';
import { loadMobileAssets } from '../src/main/remote/mobileAssets';
import { FixtureSpeechService as SpeechService } from './helpers/speechSocket';
import { SpeechPreferences } from '../src/main/settings/SpeechPreferences';
import { RemoteSpeechService } from '../src/main/application/RemoteSpeechService';
import { RemoteApiError, type RemoteCommandContext } from '../src/main/application/AdeApplicationService';

let passed=0; let failed=0;
const check=(name:string,ok:boolean)=>{if(!ok)throw new Error(name);passed++;console.log(`  ok ${name}`);};
async function rejects(name:string, action:()=>unknown, code:string) {try{await action();}catch(error){check(name,error instanceof RemoteApiError && error.code===code);return;}throw new Error(name);}
const root=mkdtempSync(join(tmpdir(),'ade-mobile-speech-')); let browser:Browser|undefined; let server:HostApiServer|undefined; let sessions:BrowserSessions|undefined; let proxy:Awaited<ReturnType<typeof mobileTlsProxy>>|undefined;
void (async()=>{
  const female='femaleVoice0000000001'; const male='maleVoice000000000001'; let generations=0; let lastDelivery: Record<string, unknown> = {};
  const fixture=createRemoteWorkspaceFixture(root,{},store=>{
    const engine=new SpeechService(store,()=> 'fixture-provider-secret',async (url,init)=>{
      check('provider key stays in main and provider URL is fixed',String(url).startsWith('https://api.elevenlabs.io/') && (init?.headers as Record<string,string>)['xi-api-key']==='fixture-provider-secret');
      if(String(url).endsWith('/voices'))return Response.json({voices:[{voice_id:female,name:'Sarah Fixture',labels:{gender:'female'}},{voice_id:male,name:'Roger Fixture',labels:{gender:'male'}}]});
      lastDelivery=JSON.parse(String(init?.body)).voice_settings; generations++;return new Response(readFileSync(resolve('scripts/fixtures/speech-silence.mp3')),{headers:{'content-type':'audio/mpeg'}});
    });return new RemoteSpeechService(new SpeechPreferences(store,engine),engine);
  });
  const {application:app,store,devices}=fixture;
  proxy=await mobileTlsProxy();sessions=new BrowserSessions(devices);
  server=new HostApiServer(app,{port:0,heartbeatMs:200,requireDeviceReads:true,authorizer:new RemoteAuthorizer('t'.repeat(32),[],undefined,devices),browser:{origin:proxy.origin,sessions,assets:loadMobileAssets(resolve(process.env.ADE_MOBILE_ASSETS ?? 'out/mobile'))},audit:entry=>devices.audit(entry)});
  proxy.target((await server.start()).port);
  browser=await chromium.launch({args:['--ignore-certificate-errors','--host-resolver-rules=MAP ade-mobile.fixture.ts.net 127.0.0.1']});
  const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true,ignoreHTTPSErrors:true});page.setDefaultTimeout(25_000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(sessions.beginPairing(proxy.origin).url);await page.getByRole('button',{name:'Dieses Gerät verbinden',exact:true}).click();
  await page.getByRole('status').filter({hasText:/^Verbunden$/}).waitFor();
  const deviceId=devices.activeDevices()[0]!.id;
  const context=():RemoteCommandContext=>({principal:{id:deviceId,kind:'device',proof:'device-signature',scopes:new Set(devices.activeDevices().find(d=>d.id===deviceId)!.scopes)},idempotencyKey:randomUUID(),requestId:'speech-fixture'});
  await page.getByRole('button',{name:'Einstellungen',exact:true}).click();await page.getByRole('tab',{name:'Stimme',exact:true}).click();
  const settings=page.getByRole('dialog',{name:'Einstellungen',exact:true}); const speech=settings.getByRole('region',{name:'Sprachausgabe',exact:true});
  await speech.getByRole('button',{name:'Stimmen laden',exact:true}).click();await speech.getByRole('alert').waitFor();
  check('mobile settings explain the dedicated voice grant', (await speech.getByRole('alert').innerText()).includes('Freigabe'));
  await rejects('missing grant cannot generate speech',()=>app.remoteSpeech(context(),{operation:'test',target:{kind:'default'},voiceId:female},true),'scope_not_granted');
  devices.setAdminScopes(deviceId,['speech:control','workspace:read']);
  await speech.getByRole('button',{name:'Stimmen laden',exact:true}).click();await speech.getByLabel('Stimme',{exact:true}).waitFor();
  check('tablet shows female inherited default', (await speech.innerText()).includes('Sarah Fixture') && (await speech.innerText()).includes('weibliche Vorauswahl'));
  await speech.getByLabel('Stimme',{exact:true}).selectOption(male);await speech.getByText('Stimmenauswahl gespeichert.',{exact:true}).waitFor();
  check('tablet saves the global voice in the host profile',store.get().settings.speechVoiceId===male);
  await speech.getByRole('button',{name:'Stimme testen',exact:true}).click();await speech.getByText('Stimmtest vollständig abgespielt.',{exact:true}).waitFor();
  check('mobile CSP permits actual MP3 playback',await speech.getByLabel('Stimmtest Wiedergabe').evaluate(node=>(node as HTMLAudioElement).ended));
  check('tablet displays the shared stability default',await speech.getByRole('slider',{name:'Stabilität',exact:true}).inputValue()==='0.9');
  await speech.getByRole('slider',{name:'Stabilität',exact:true}).fill('0.65');
  check('tablet names v3 without pronunciation notes or unsupported controls', (await speech.innerText()).includes('Eleven v3') && !(await speech.innerText()).includes('Aussprachevorgabe') && await speech.getByRole('slider').count() === 1);
  await speech.getByRole('button',{name:'Stimme testen',exact:true}).click();
  await speech.getByText('Stimmtest vollständig abgespielt.',{exact:true}).waitFor();
  check('tablet previews native parameters without saving',lastDelivery.stability===0.65 && Object.keys(lastDelivery).join()==='stability' && !store.get().settings.speechTuning);
  await speech.getByRole('button',{name:'Parameter speichern',exact:true}).click();
  await speech.getByText('Stimmparameter gespeichert. Gilt auf PC und Tablet.',{exact:true}).waitFor();
  check('tablet persists tuning in the PC configuration',store.get().settings.speechTuning?.stability===0.65);
  await rejects('selected agent target cannot write global tuning',()=>app.remoteSpeech(context(),{operation:'select',target:{kind:'agent',agentId:'builder'},voiceId:female,tuning:store.get().settings.speechTuning},true),'invalid_payload');
  let dropped=false;
  let finishDrop!: () => void;
  const dropFinished = new Promise<void>(resolve => { finishDrop = resolve; });
  await page.route('**/api/v1/speech/command',async route=>{const command=route.request().postDataJSON();if(!dropped && command.operation==='test'){
    dropped=true;
    const url = new URL(route.request().url()); const host = url.host; url.hostname = '127.0.0.1';
    await route.fetch({url:url.href,headers:{...route.request().headers(),host}});
    await route.abort('connectionfailed'); finishDrop();
  }else await route.continue();});
  await speech.getByRole('button',{name:'Stimme testen',exact:true}).click();await settings.getByRole('region',{name:'Offene Sprachaktion',exact:true}).waitFor();
  await dropFinished;
  await page.reload();await page.getByRole('status').filter({hasText:/^Verbunden$/}).waitFor();await page.getByRole('button',{name:'Einstellungen',exact:true}).click();await page.getByRole('tab',{name:'Stimme',exact:true}).click();
  const generationBefore=generations;
  await settings.getByRole('button',{name:'Sprachaktion erneut prüfen',exact:true}).click();await speech.getByText('Stimmtest vollständig abgespielt.',{exact:true}).waitFor();
  check('lost paid test reply survives reload and replay does not generate again',dropped && generations===generationBefore);
  await speech.getByRole('button',{name:'Stimmen laden',exact:true}).click();
  check('saved tablet tuning survives reload',await speech.getByRole('slider',{name:'Stabilität',exact:true}).inputValue()==='0.65');
  check('provider key never reaches browser storage or content',!await page.evaluate(()=>JSON.stringify({...localStorage}).includes('fixture-provider-secret') || document.body.innerText.includes('fixture-provider-secret')));
  const select={operation:'select',target:{kind:'agent',agentId:'builder'},voiceId:female};
  await app.remoteSpeech(context(),select,true);
  check('agent-specific voice saves independently of global default',store.get().agents.find(a=>a.id==='builder')!.speechVoiceId===female && store.get().settings.speechVoiceId===male);
  const ledgerText=readFileSync(join(root,'remote','commands.json'),'utf8');
  check('durable receipts do not retain audio or credentials',!ledgerText.includes('base64') && !ledgerText.includes('fixture-provider-secret'));
  const restricted=context();devices.setAdminScopes(deviceId,['speech:control','workspace:read'],{mode:'selected',agentIds:['builder'],repositoryIds:[]});
  await rejects('selected devices cannot change global voice',()=>app.remoteSpeech(restricted,{operation:'select',target:{kind:'default'},voiceId:female},true),'scope_not_granted');
  await rejects('selected devices cannot inspect another agent voice',()=>app.remoteSpeech(restricted,{operation:'voices',target:{kind:'agent',agentId:'reviewer'}},false),'scope_not_granted');
  await rejects('unsigned principal cannot use speech',()=>app.remoteSpeech({...context(),principal:{id:'bootstrap',kind:'bootstrap-token',proof:'bearer',scopes:new Set(['read'])}},{operation:'voices',target:{kind:'default'}},false),'device_proof_required');
  await page.setViewportSize({width:390,height:844});check('mobile speech settings fit a phone',await settings.evaluate(node=>node.scrollWidth<=node.clientWidth+1));
  await page.keyboard.press('Escape');await settings.waitFor({state:'hidden'});
  check('closing settings restores the visible settings opener',await page.getByRole('button',{name:'Einstellungen',exact:true}).evaluate(node=>node===document.activeElement));
  devices.setAdminScopes(deviceId,['speech:control','workspace:read'],{mode:'all'});
  await page.getByRole('button',{name:'Workspace für Builder',exact:true}).click();
  const workspace=page.getByRole('dialog',{name:'Workspace · Builder',exact:true});
  await workspace.getByRole('button',{name:'Agent-Profil',exact:true}).click();
  const agentSpeech=workspace.getByRole('region',{name:'Agent-Stimme',exact:true});
  await agentSpeech.getByRole('button',{name:'Stimmen laden',exact:true}).click();
  await agentSpeech.getByLabel('Stimme',{exact:true}).waitFor();
  check('mobile agent profile displays its own voice',await agentSpeech.getByLabel('Stimme',{exact:true}).inputValue()===female);
  await agentSpeech.getByLabel('Stimme',{exact:true}).selectOption('');
  await agentSpeech.getByText('Stimmenauswahl gespeichert.',{exact:true}).waitFor();
  check('tablet can reset an agent to the inherited ADE voice',store.get().agents.find(a=>a.id==='builder')!.speechVoiceId===undefined && (await agentSpeech.innerText()).includes('Roger Fixture'));
  await page.keyboard.press('Escape');await workspace.waitFor({state:'hidden'});
  devices.setAdminScopes(deviceId,['speech:control','workspace:read','catalog:write','projects:write'],{mode:'all'});
  const projectId=(await app.administer(context(),{operation:'project-create',input:{name:'Voice project'}})).created!.id;
  await page.getByRole('tab',{name:'Projekte',exact:true}).click();
  await page.getByRole('button',{name:'Projektordner aktualisieren',exact:true}).click();
  await page.getByRole('button',{name:'Workspace öffnen: Voice project',exact:true}).click();
  const project=page.getByRole('dialog',{name:'Projekt · Voice project',exact:true});
  await project.getByRole('button',{name:'Workspace öffnen',exact:true}).click();
  await project.getByRole('button',{name:'Projekt-Einstellungen',exact:true}).click();
  const projectSpeech=project.getByRole('region',{name:'Projekt-Stimme',exact:true});
  await projectSpeech.getByRole('button',{name:'Stimmen laden',exact:true}).click();
  await projectSpeech.getByLabel('Stimme',{exact:true}).selectOption(female);
  await projectSpeech.getByText('Stimmenauswahl gespeichert.',{exact:true}).waitFor();
  check('tablet project settings persist a voice without changing the global default',store.get().repositories.find(r=>r.id===projectId)!.speechVoiceId===female && store.get().settings.speechVoiceId===male);
  await projectSpeech.getByLabel('Stimme',{exact:true}).selectOption('');
  await projectSpeech.getByText('Stimmenauswahl gespeichert.',{exact:true}).waitFor();
  check('tablet project can inherit the global voice again',store.get().repositories.find(r=>r.id===projectId)!.speechVoiceId===undefined && (await projectSpeech.innerText()).includes('Roger Fixture'));
  await page.keyboard.press('Escape');await project.waitFor({state:'hidden'});
  // Voice studio (casual conversation): a compared variant can become the ADE default voice from the tablet.
  await page.locator('#mobile-supervision').click();await page.locator('#conversation-mode-casual').click();
  const casual=page.getByRole('dialog',{name:'Plaudern & Stimme',exact:true});await casual.waitFor();
  // The studio opens by itself, loads the voices and seats the PC's default voice; the sample text is suggested, not required.
  const studio=casual.locator('details.voice-studio');await studio.getByTestId('voice-studio-default').getByText('Standardstimme',{exact:false}).waitFor();
  check('the studio names the current default voice without a click',(await studio.getByTestId('voice-studio-default').textContent())!.includes('Standardstimme'));
  check('the sample text is suggested as a placeholder and a badge marks the default variant',!!(await studio.getByLabel('Hörprobentext',{exact:true}).getAttribute('placeholder')) && await studio.locator('.voice-studio-badge').first().isVisible());
  await studio.getByLabel('Variante A: Stimme',{exact:true}).selectOption(female);
  check('the studio offers to make a variant the default voice',await studio.getByRole('button',{name:'A als Standardstimme übernehmen',exact:true}).isEnabled());
  await studio.getByRole('button',{name:'A als Standardstimme übernehmen',exact:true}).click();
  await studio.getByText('Variante A ist jetzt die Standardstimme',{exact:false}).waitFor();
  check('voice studio variant becomes the ADE default voice on the PC',store.get().settings.speechVoiceId===female);
  check('the default badge follows the new default and the select button disappears on that variant',(await studio.locator('fieldset').first().textContent())!.includes('Standardstimme') && await studio.getByRole('button',{name:'A als Standardstimme übernehmen',exact:true}).count()===0);
  await page.keyboard.press('Escape');await casual.waitFor({state:'hidden'});
  check('mobile speech flow has no uncaught browser errors',errors.length===0);
})().catch(async error=>{failed++;console.error(error); const page=browser?.contexts()[0]?.pages()[0]; if(page) {console.error((await page.locator('body').innerText()).slice(-6000));await page.screenshot({path:resolve('test-results/mobile-speech-failure.png')});}}).finally(async()=>{await browser?.close();await server?.stop();sessions?.dispose();await proxy?.close();rmSync(root,{recursive:true,force:true});console.log(`Mobile speech browser: ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;});
