import { randomUUID } from 'node:crypto';
import { ConversationDrafts, conversationDraftKey, type PendingConversationCommand } from '../src/renderer/conversation/conversationDrafts';
import { clearDeviceDrafts } from '../src/mobile/deviceDrafts';
let passed = 0; let failed = 0;
const check = (name: string, ok: boolean) => { if (ok) { passed++; console.log(`  ok  ${name}`); } else { failed++; console.error(`FAIL  ${name}`); } };
const refuses = (fn: () => unknown) => { try { fn(); return false; } catch { return true; } };
const values = new Map<string, string>();
const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, text: string) => { values.set(key, text); }, removeItem: (key: string) => { values.delete(key); } };
Object.defineProperty(globalThis, 'localStorage', { value: storage, configurable: true });
const make = (scope = 'desktop') => new ConversationDrafts(storage, scope);
const first = randomUUID(); const second = randomUUID(); const drafts = make();
check('new origin has no guessed conversation or pending action', drafts.read().selected === '' && !drafts.read().pending.length);
drafts.select(first); drafts.edit(first, 'First text'); drafts.edit(second, 'Second text');
check('reload keeps conversation selection and two isolated drafts', make().read().selected === first && make().text(first) === 'First text' && make().text(second) === 'Second text');
const input: PendingConversationCommand = { operation: 'send', conversationId: first, afterTurnId: null, commandId: randomUUID(), text: 'First text' };
drafts.reserve(input);
check('lost send reply restores the exact command key, target and parent turn', JSON.stringify(make().pending(first)) === JSON.stringify(input));
check('pending delivery cannot be silently replaced by another message', refuses(() => drafts.reserve({ ...input, text: 'Other' })));
drafts.reserve(input);
check('same-key retry adds no second pending entry', drafts.read().pending.length === 1);
const receipt = { conversationId: first, turnId: randomUUID(), replayed: true };
check('foreign acknowledgement cannot clear the accepted draft', refuses(() => drafts.acknowledge(input, { ...receipt, conversationId: second })) && !!drafts.pending(first));
drafts.acknowledge(input, receipt);
check('confirmed delivery clears only the original target draft and pending request', !make().pending(first) && make().text(first) === '' && make().text(second) === 'Second text');
drafts.acknowledge(input, receipt);
check('late duplicate acknowledgement leaves another draft intact', drafts.text(second) === 'Second text');
drafts.edit(first, 'First text'); drafts.reserve(input); drafts.edit(first, 'A newer unsent note');
drafts.acknowledge(input, receipt);
check('late acknowledgement cannot erase text edited by another open view', drafts.text(first) === 'A newer unsent note');
const creation: PendingConversationCommand = { operation: 'create', profileId: 'profile', commandId: randomUUID() };
drafts.reserve(creation);
check('creation survives dialog close before its result ID is known', make().pending('create')?.commandId === creation.commandId);
drafts.acknowledge(creation, { conversationId: second, turnId: null, replayed: true });
check('late creation acknowledgement cannot replace a newer explicit selection', make().read().selected === first && !make().pending('create'));
make('mobile:tablet').reserve(input); make('mobile:tablet').edit(first, 'Tablet draft');
check('device and desktop drafts never share a pending command or text', !make('mobile:other').pending(first) && drafts.text(first) === 'A newer unsent note');
clearDeviceDrafts('tablet');
check('forgetting a device removes its conversation recovery data only', !values.has(conversationDraftKey('mobile:tablet')) && make().text(second) === 'Second text');
check('question answers are never accepted into persisted recovery', refuses(() => drafts.reserve({ operation: 'answer', conversationId: first, turnId: randomUUID(), questionId: 'q', commandId: randomUUID(), answers: { q: { answers: ['secret'] } } } as unknown as PendingConversationCommand)));
const legacy = randomUUID(); storage.setItem(`ade:conversation-draft:${legacy}`, 'Original legacy draft');
check('first desktop implementation drafts remain readable', drafts.text(legacy) === 'Original legacy draft');
drafts.edit(legacy, ''); check('cleared legacy text does not reappear on reopening', make().text(legacy) === '');
const valid = storage.getItem(conversationDraftKey('desktop'))!;
storage.setItem(conversationDraftKey('desktop'), '{broken');
check('malformed recovery is preserved and prevents new dispatch reservation', refuses(() => drafts.reserve(input)) && storage.getItem(conversationDraftKey('desktop')) === '{broken');
storage.setItem(conversationDraftKey('desktop'), JSON.stringify({ version: 1, selected: first, drafts: [], pending: [input, input] }));
check('duplicate recovery identities fail closed', refuses(() => drafts.read()));
storage.setItem(conversationDraftKey('desktop'), 'x'.repeat(1024 * 1024 + 1));
check('oversized recovery is bounded before parsing', refuses(() => drafts.read()));
const unavailable = new ConversationDrafts({ getItem: () => null, setItem: () => { throw new Error('quota'); } }, 'desktop');
check('storage denial fails before a pending request can be admitted', refuses(() => unavailable.reserve(input)));
storage.setItem(conversationDraftKey('desktop'), valid); drafts.reserve(input); drafts.rejected(input);
check('confirmed refusal releases the retry key while preserving the unsent text', !drafts.pending(first) && drafts.text(first) === 'A newer unsent note');
storage.setItem(conversationDraftKey('desktop'), valid); drafts.reserve(input); drafts.acknowledge(input, receipt);
check('final positive recovery remains writable after all negative controls', !drafts.pending(first) && drafts.text(second) === 'Second text');
console.log(`Conversation drafts: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
